### ISSUE TITLE
Consider adding bitlocker to the list

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#1]
I know that Access Manager is mostly about LAPS, but maybe consider adding Bitlocker keys support? It's similarly critical (and just another field in AD) and would be great to have it accessible via Access Manager

**Comment by ryannewington** [comment]
This is an excellent idea. Here I was thinking I was finished with my scope creep. 🤣 

I have to get the first beta out, so we can start testing the core, and then I'll add this in.

**Comment by PrzemyslawKlys** [comment]
That's great! MBAM is on it's way out and people are looking for solutions! Thank you for considering ;)

**Comment by ryannewington** [comment]
I'll have something up and running to test with in a couple of weeks at most. This is _relatively_ easy to do because the extensibility is built in already.

**Comment by ryannewington** [comment]
![image](https://user-images.githubusercontent.com/17229877/90484485-95476d00-e179-11ea-811a-a07dd53ef831.png)

**Comment by PrzemyslawKlys** [comment]
Tada! Amazing :-)

**Comment by PrzemyslawKlys** [comment]
Now all you need to do is rotate the key when done :-)

**Comment by ryannewington** [comment]
Stop suggesting features or this will never get released

**Comment by sylwester-majcher** [comment]
Hi Ryan,
Question. It means access to laps pwd eq access to bitlocker key for the specific computer? Is it the same set of permissions?

Pozdrawiam
Sylwester Majcher
________________________________
Od: Ryan Newington <notifications@github.com>
Wysłane: Tuesday, August 18, 2020 9:48:29 AM
Do: lithnet/access-manager <access-manager@noreply.github.com>
DW: Subscribed <subscribed@noreply.github.com>
Temat: Re: [lithnet/access-manager] Consider adding bitlocker to the list (#1)


Stop suggesting features or this will never get released

**Comment by ryannewington** [comment]
All permissions are separate. You can grant LAPS, LAPS history, JIT and bit locker all individually.

Users will only see the options they have been granted access to. So if you only give someone LAPS access, they won't even see the other options.

**Comment by sylwester-majcher** [comment]
Thanks a lot. It sounds really perfect.

Pozdrawiam
Sylwester Majcher
________________________________
Od: Ryan Newington <notifications@github.com>
Wysłane: Tuesday, August 18, 2020 1:13:33 PM
Do: lithnet/access-manager <access-manager@noreply.github.com>
DW: sylwester-majcher <sylwester.majcher@outlook.com>; Comment <comment@noreply.github.com>
Temat: Re: [lithnet/access-manager] Consider adding bitlocker to the list (#1)


All permissions are separate. You can grant LAPS, LAPS history, JIT and bit locker all individually.

Users will only see the options they have been granted access to. So if you only give someone LAPS access, they won't even see the other options.

**Comment by ryannewington** [comment]
Admins will see this and grant permissions to users
![image](https://user-images.githubusercontent.com/17229877/90510175-d2255b00-e19d-11ea-8d0f-0dad7957c86c.png)

User will see this (depending on the permissions they have, some options may not appear)
![image](https://user-images.githubusercontent.com/17229877/90510127-c043b800-e19d-11ea-96e6-9b11500715f3.png)

**Comment by ryannewington** [comment]
Feature is complete, so closing this issue
