### ISSUE TITLE
Disable TLS 1.0 and TLS 1.1 for Access Manager Website

### ISSUE THREAD

**Issue by astular** [lithnet/access-manager#100]
Hello!
Access Manager website is by default rated as B on ssllabs.com SSL Server Test tool.

Is it possible to disable TLS 1.0 and TLS 1.1 for Access Manager website?

I have tried to disable the protocols with the IISCrypto Tools, but it doesn't effect Access Manager. 

I have also tried to enhance .NET security by adding the following keys in the registry:
_Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001_

I think that disabling TLS 1.0 and TLS 1.1 can only be done programatically, in the code. Could you perhaps provide a setting to force TLS 1.2 or newer?

Kind regards!
Anze

PS: Lithnet Access Manager is a great solution. Good job! Kudos!

**Comment by jaysnrye** [comment]
Hi @astular 

You can try setting the following as best practice 

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
```

You should also ensure Access Manager is not accessible from the internet.  That would be bad.

**Comment by ryannewington** [comment]
Just to add, the `Microsoft.NETFramework` registry keys aren't in play here, as this is a .NET core app, rather than .NET framework. 

Because the app uses Microsoft's HTTP.SYS engine (the same as IIS), we don't have a programmatic way to disable legacy protocols. It has to be done server-wide. The reg settings Jaysn provided are the correct ones to disable TLS 1.0 and 1.1 server-wide, and they are the same ones IISCrypto would be setting. It does require a machine restart to take effect.

I have noticed SSLlabs caching recent results in the past, so do check the run date/time and make sure it's given you an up-to-date-result after running this.
