### ISSUE TITLE
Password History Access

### ISSUE THREAD

**Issue by carlosalbaidiada** [lithnet/access-manager#102]
Hi,

thanks for this great tool

I've implement it following you guide and it's working fine.

But, password history is not showed as a request, is working for Bitlocker, current local admin password and JIT ... but not the history

The GPO is applying and I can see values on AD attribute ... the efective access shows not allowed on Password history but it's finde on the other ones.

Thanks a lot

**Comment by jaysnrye** [comment]
Hi @carlosalbaidiada 

Can you double check the permissions for the service account on the OU your computer's live in?

You can generate a script to set these for you on the local administrator password tab by clicking 'Delegate Lithnet AMA Permissions'.
Be sure to make sure you update the OU in the script to the current location.

If the permissions are correct you might be able to find a clue in the access manager service log.

**Comment by jaysnrye** [comment]
Also note that it will take time to populate the history attribute. The current password will need to expire and a new one generated before the history attribute is populated. If you have recently installed AMS, there may not be any passwords to show yet.

**Comment by jaysnrye** [comment]
If you are on the current version of Access Manager, you'll actually need an enterprise edition license to access laps history. You can reach out to support@lithnet.io and they can get you a trial license

**Comment by carlosalbaidiada** [comment]
Thanks a lot for the quick response 

My fault, I didn't read that is a Enterprise license feature sorry.

Now I have a new issue regarding authentication. I see Azure AD authentication and after create the App Registration on Azure.

It works only from my computer and fails everywhere I try. I followed the instructions and I'm sure that the redirected URI is no localhost. But is still working just when I try from my computer.

Thanks in advance

![image](https://user-images.githubusercontent.com/66850681/121168592-6b1f8280-c853-11eb-962c-90164271c684.png)

**Comment by ryannewington** [comment]
Hi @carlosalbaidiada 

What the reply URL you specified in the AzureAD app registration? Is it in the format of  `https://hostname.com/auth`?

**Comment by carlosalbaidiada** [comment]
Yes indeed,

This the current format

Regards

**Comment by ryannewington** [comment]
And just to be 100% sure, there is no trailing slash on the end of that URL?

**Comment by carlosalbaidiada** [comment]
I’ve check it right now … and there is no slash at the end.

**Comment by ryannewington** [comment]
When you say that it is working from your computer, are you using the same URL in your browser as you are on the other computers?

You may need to check the AAD logs for the specifics around what URL is being presented to AAD and compare that to what is expected in the app registration.

**Comment by carlosalbaidiada** [comment]
Thanks, I’ll check it

Actually is very frustrating, because if I run it from my computer works like a charm, but even with my credentials … if I try it on a different computer pointing to the same URL … I get this message

Regards
