### ISSUE TITLE
Reinstall of AMS service removed the firewall rule permitting traffic on 80/443

### ISSUE THREAD

**Issue by s881628** [lithnet/access-manager#12]
The initial install creates a firewall rule to permit traffic inbound on 80/443.
Reinstalling the AMS service over the top of the existing install removes this firewall rule.

**Steps to reproduce**

1. Install the AMS service
2. Use a newer build of the installer to reinstall/update the previous install
3. Note the firewall rule permitting web access has been deleted.

**Expected result**
Firewall rule should remain after the upgrade/reinstall

**Actual result**
Firewall rule has been deleted after the upgrade/reinstall causing client to be unable to access the web portal

**Comment by ryannewington** [comment]
Resolved in recent installers
