### ISSUE TITLE
Automatic JIT Group Creation not working as expected.

### ISSUE THREAD

**Issue by RygenX01** [lithnet/access-manager#121]
Hi,
If I use "Automatic JIT Access Group Creation" it seems that every entry added after the first entry does not automatically create a group in Active Directory. 
The first entry I create, automatically creates a AD Group (in a designated OU) for the Computers found in a OU. I selected the global Computer OU which contains multiple OU's for different types of servers and selected the child containers option.
The second entry added does not create a AD Group (in a different designated OU than the first entry) for the server found in the childern of the global computers OU.
This also applies for a third entry and so on.
After adding a entry I selected the entry and called for the "delegate permissions" button to get the PowerShell script and run it against AD.
Permissions seem fine, if i remove the first entry from automatic JIT Group Creation, the second entry (which is the only one left) starts working
The names of the AD groups that need to be created are not equal.
Also every time I process a change I save the AMS config and stop/start the service.
In the JIT-worker log I cannot find anything about the second entry i created, only message for the first entry seem to appear.

What does work: when i create 2 entries and the "Computer OU" is specified to one of the child OU's (for each entry a different child OU). Then it creates one AD group for each server in the separate OU's. (so the second entry could work)
If I select the same child OU for the second entry it still does not work, even if I select the option to not look at the Child OU's
This is tested against a 2012 R2 forest and domain functional level.

Hopefully you can help me figure out what's wrong. Or if my view of how this works is wrong.

Kind Regards,
Rik

**Comment by jaysnrye** [comment]
Hi @RygenX01 

AMS will create a JIT group for each server. This is the group that gets added to the local administrator group on each server.
When creating an authorisation rule, you define the JIT group the user gets added to. That group you define in the rule creation process does not create any additional groups, it merely tells AMS which JIT group the requesting user needs to be a member of to gain admin access to to the server.
The user it removed from the JIT group automatically after the predefined time.
If you want to assign users access to a server who are part of a group, you need to create that group yourself in AD, add the users to it, then use that group in your authorisation rule. When a member of that authorisation group requests access, they will be added to the previously automatically created JIT group, for example 'JIT-%COMPUTERNAME%'

**Comment by RygenX01** [comment]
Hi

@jaysnrye Thanks for your response. I get what your saying but my problem is not concerning the authorization part.

I found out why "Automatic JIT Access Group Creation" is not working as expected. If I disable the option _"delete the groups in this OU that do not have matching computers"_ the "Automatic JIT Access Group Creation" starts working as expected. The only downside is that if a computer account gets deleted, the corresponding AD group is not removed automatically. Now after this works I created the authorization rules to get local admin access and RDP access to one server. The idea of how RDP access with AMS could work is the same as for only using Local admin access. Unfortunately, if I run through the JIT website with a test user, only the for local admin AD group is created (dynamic/time based group) and not the second group for RDP.

Is this expected behavior, or could this work using 2 authorization rules for one unique user, setting localadmin and RDP access on one specific server?

Kind Regards,
Rik

**Comment by ryannewington** [comment]
Hi Rik,

I think I understand what you mean about the automatic group creation not working. I have a feeling I have fixed this in the upcoming V2 release. I'll have a look and see if I can back port the fix to the current version for you.

I must admit I'm still a bit confused about the second part of your message. Could you walk me through what you are trying to achieve here as a starting point

________________________________

**Comment by RygenX01** [comment]
Hi Ryan, 

I'm implementing localadmin privileges via JIT and I also want to use JIT to implement RDP access privileges.
So if a user logs in to the AMS website and enables JIT, JIT should configure the rights to have local admin access and RDP access for a specific server. This works for the local admin access part. 

For this I create an authorization rule for user X and server1. The authorization rule creates a dynamic group containing the user and nests this group in the group which is created by "Automatic JIT Access Group Creation". This group is then applied by GPO's to local "Administrators" group on the server.

If I create a second authorization rule for user X and server1 and want to do the same thing for RDP access, the dynamic group is not created and therefor not nested in the group which is created by "Automatic JIT Access Group Creation". The Group create by "Automatic JIT Access Group Creation" is in turn used in a GPO to configure RDP Access

Hopefully the this is more clear.

Kind Regards
Rik

**Comment by ryannewington** [comment]
If user1 has admin rights on server x, they automatically have RDP access as well. What is the second group going to achieve? Unless you have modified default permissions on the server for administrators to remove the right for RDP logon? If that's the case your better off adding the same JIT group to both local admins and RDP users via GPO, and having only one group created per computer.

Some info on how the authorisation engine works: The authorisation engine looks for the first match between user and computer and the access requested. If it matches your "admin" rule, it's never going to process your "RDP" rule.  So you're not going to be able to get AMS to add the user to multiple groups.



________________________________

**Comment by RygenX01** [comment]
Hi Ryan, 
Thanks for your clarification. 

We are also have situations were non-administrator users login to some servers for performing some tasks. But this can be achieved by leaving them out of the local admin groups and just give them RDP access, which will be the first authorization rule that hits leaving me with no problem to discuss about.

I will close the questions, Thanks!
Kind Regards,
Rik

**Comment by ryannewington** [comment]
Hi Rik,

Yep, that should work. We are considering native jit support for other roles such as RDP, so I will reach out if and when we have something there for you to try.

Ryan
