### ISSUE TITLE
Healthcheck ability?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#128]
**Is your feature request related to a problem? Please describe.**
We would like to add monitoring that website/system is working correctly. Is there some kind of health check available to check for service state like for example Exchange provides? This is so during publish we can actually monitor the service. 

**Describe the solution you'd like**
Ability to query certain URL for health check information

**Comment by ryannewington** [comment]
Are you thinking just a URL endpoint that returns a 200 OK or something more detailed?

**Comment by PrzemyslawKlys** [comment]
Yes, an endpoint that a proxy/monitoring can check.

**Comment by ryannewington** [comment]
Can do! Do you have a need for this today with v1 customers, or can we just add it to V2 (beta being released this weekend)?

**Comment by PrzemyslawKlys** [comment]
In your own time :-) I won't deploy it for another week or anything. Wasn't even counting for instant fix :)

**Comment by ryannewington** [comment]
I've added capability to v2. You can just hit the /health-check endpoint for a 200 response if it is healthy, or 503 if its not healthy.

The [beta has been released](https://github.com/lithnet/access-manager/releases/tag/v2.0.8393-beta1)

The health check function doesn't require an enterprise license.

However, if you want an enterprise edition license key to try the other features, just send me your AD DNS forest name to support@lithnet.io and we'll get it organized.
