### ISSUE TITLE
Installer incorrectly proceeding with .NET core versions > 3

### ISSUE THREAD

**Issue by marcohald** [lithnet/access-manager#133]
**Describe the bug**
The Installer does a prerequisite check on launch and did not report any error.
But the installation failed every time at the end where the Service should be registered

**To Reproduce**
Install the 'Microsoft.NETCore.App' in Version 5.0.13

When i executed this Command "C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Service.exe" I got this Error
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.22' was not found.
  - The following frameworks were found:
      5.0.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
```

The error is very specific but it is displayed nowhere.

**Expected behavior**
The Setup should create a MSI Logfile ( I needed to call the extracted MSI manually like `msiexec /i Lithnet.AccessManager.Service.Setup.msi /L*V "C:\lithnet.log"` )
The MSI Log should contain the output of the exe that exited with an error code
The Setup should warn if the Microsoft.NETCore.App has the wrong version

**Access Manager installation**
 - OS: Windows Server 2019
 - Version 1.0.7925.0

**Logs**
```
MSI (s) (80:28) [10:01:00:925]: Executing op: ActionStart(Name=InstallService,Description=Installing service,Template=Installing service lithnetams)
Action 10:01:00: InstallService. Installing service
MSI (s) (80:28) [10:01:00:926]: Executing op: CustomActionSchedule(Action=InstallService,ActionType=1042,Source=C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Service.exe,Target=setup install-service "DOMAIN\erviceAccount$" "",)
CustomAction InstallService returned actual error code -2147450730 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (80:28) [10:01:01:228]: Note: 1: 1722 2: InstallService 3: C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Service.exe 4: setup install-service "DOMAIN\erviceAccount$" "" 
```

**Comment by ryannewington** [comment]
@marcohald 

Thanks very much for reporting this. It does look like the installer is looking for .NET Core >= 3, when it must look for .NET core = 3 only.

I'll update this in a future release.
