### ISSUE TITLE
GMSA script update

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#14]
Here's a version with more error checking and making sure KDS key actually exists and is older than 10 hours. I have quite a new domain and KDS wasn't generated. Once it generated new-service account was providing errors:
- https://social.technet.microsoft.com/Forums/ie/en-US/82617035-254f-4078-baa2-7b46abb9bb71/newadserviceaccount-key-does-not-exist?forum=winserver8gen

1. Fixes requirement $ in ComputerName 
2. Checks for the existence of said computer
3. Checks for KDS Key Time
4. I am not sure if you can use : for AccountNotDelegated as it's a nullable bool parameter, not a switch, but maybe I don't use weird ways of doing things. I also believe KerberosEncryptionType is an array, not a string of elements - could be wrong here. 
5. I've not been able to test this yet as I've not passed 10 hours yet, so may need to adjust this once this goes thru. 
6. Generally stops on errors and displays warnings. I really don't like red color on screen, and in this case it would continue executing even if errors occurred. 

Let me know if that makes sense.

```powershell
# Create-GroupManagedServiceAccount
#
# This script enables the KDS service in the domain if it is not already enabled,
# and creates a new group-managed service account to use with the Access Manager service
#
# This script requires membership in the Domain Admins group
#
# Version 1.0

#-------------------------------------------------------------------------
# Set the following values as appropriate for your environment
#-------------------------------------------------------------------------

$amsServerName = "ComputerName"
$accountName = "ADAccess"
$description = "Service account for the Lithnet Access Manager Service"

#-------------------------------------------------------------------------
# Do not modify below here
#-------------------------------------------------------------------------

try {
    $ComputerExists = Get-ADComputer -Identity $amsServerName -ErrorAction Stop
} catch {
    Write-Warning "Computer account $amsServerName doesn't exists. Terminating."
    return
}

$DateNow = Get-Date
$RootKey = Get-KdsRootKey
if (-not $RootKey) {
    Write-Host "Generating KDS Root Key" -ForegroundColor Green
    Add-KdsRootKey -EffectiveImmediately
}
$RootKey = Get-KdsRootKey
if (-not $RootKey) {
    Write-Warning "KDS Root Key not available. Terminating."
    return
}
if (($RootKey.CreationTime).AddHours(10) -gt $DateNow) {
    Write-Warning "KDS Root Key is too young to proceed. Please wait at least 10 hours after generating KDS key"
    return
}

try {
    New-ADServiceAccount -Name $accountName -AccountNotDelegated $true -Description $description -Enabled $true -KerberosEncryptionType AES256, AES128 -SamAccountName $accountName -RestrictToOutboundAuthenticationOnly -ErrorAction Stop
} catch {
    Write-Warning "New-ADServiceAccount - Error creating GMSA account. Terminating with error: $($_.Exception.Message)"
    return
}
try {
    Set-ADServiceAccount -Identity $accountName -PrincipalsAllowedToRetrieveManagedPassword $ComputerExists.SamAccountName
} catch {
    Write-Warning "Set-ADServiceAccount - Error assigning GMSA account. Terminating with error: $($_.Exception.Message)"
    return
}

$serviceAccountName = "$((Get-ADDomain).NetbiosName)\$accountName$"

Write-Host "You may need to wait for all domain controllers in the domain to replicate the key before you are able to use the account" -ForegroundColor Yellow
Write-Host "The service account has been created. Use $ServiceAccountName in the installer." -ForegroundColor Yellow
```

**Comment by ryannewington** [comment]
Thanks for these updates, I'll incorporate into the next build.

Should we provide an option for test environments to force the immediate availability of the key with 

`Add-KdsRootKey –EffectiveTime ((get-date).addhours(-10))`

I dont want to throw too many options at people, but at the same time, waiting 10 hours before you can install the app seems a bit annoying.

**Comment by PrzemyslawKlys** [comment]
What you mean by in the next build? The installer doesn't use it and points you to WIKI? Isn't it just an update to WIKI?

As for the -10 hours - well normally I would create a functioning git it parameter -TestDomain switch and be done with it. I can add it, just not sure what's the impact if someone decides to do this for production

**Comment by ryannewington** [comment]
Double confused. It is in the script template store in the app as well.

Were you able to test that this worked after the 10 hours? If so I'll update and publish. I've run out of domains without root keys to test on!

**Comment by PrzemyslawKlys** [comment]
I edited the script a bit since the original posting after testing and it works properly now. Had to play with the AddHours put in wrong place. And yes it worked.

**Comment by ryannewington** [comment]
Used your script as a base and made a few additional modifications. The wiki has been updated, and the in-app scripts will be in beta.2

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.
