### ISSUE TITLE
Underscore is not recognized as a supported character

### ISSUE THREAD

**Issue by timatlee** [lithnet/access-manager#140]
**Describe the bug**
When entering a computer name that contains an underscore, an error message is generated stating "The computer name contains unsupported characters"

**To Reproduce**
1. Access the Lithnet AMS website
2. Enter a computer name with an underscore:  `ct-tla_admin`
3. Provide a reason as required
4. Informational message is shown under the computer name field.

**Expected behavior**
Expected that I would be able to navigate to the next screen to select the information I want to retrieve.

LAPS UI considers this a valid computer name.

**Screenshots**
![image](https://user-images.githubusercontent.com/1431914/153049996-1a1b524c-3e65-4014-bee8-bead64a92668.png)

![image](https://user-images.githubusercontent.com/1431914/153050172-ec795e6d-453b-463a-814f-fe41cfd68ad8.png)

**Access Manager installation**
 - OS: Server 2019 Standard
 - Version 1.0.7939

**Additional context**

**Logs**
There are no relevant data in any logs that I am able to find (when searching for `ct-tla_admin`.

**Comment by ryannewington** [comment]
@timatlee Thanks for pointing this one out. It's a tricky one as an underscore is [illegal in a DNS host name](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#dns-host-names), but legal in a netBIOS name. I've at least unblocked the input validator and allow this to be accepted, but I'm not sure if it will cause other issues in the application. Basic testing seems to work.

New build is here
https://github.com/lithnet/access-manager/releases/tag/1.0.7941

**Comment by timatlee** [comment]
Hah, TIL that underscore is illegal.  I don't think I've come across that before.

New build seems to be working as expected for us.  Thanks for handling this so quick.
