### ISSUE TITLE
[HELP] Azure SSO An unexpected error occurred

### ISSUE THREAD

**Issue by sonnenx** [lithnet/access-manager#146]
Hej,

I've configured Azure SSO with https://github.com/lithnet/access-manager/wiki/Setting-up-authentication-with-Azure-AD

redirect URI: https://mydomain.com/auth

and after logging in I get

https://mydomain.com/Home/AuthNError?messageid=3

![image](https://user-images.githubusercontent.com/37338780/157118103-5962c013-3710-4822-a840-0b9498910186.png)

![image](https://user-images.githubusercontent.com/37338780/157118164-7dbbb17b-f5c4-4e89-98ec-f005db40e4a3.png)

What can be wrong?

Best,

**Comment by ryannewington** [comment]
If you check the event viewer or the access-manager-service.log file, you should see more information on the cause of this error

**Comment by sonnenx** [comment]
Hej,
Checked.
I had to generate the new secret.

Ticket to close, thanks a lot.
