### ISSUE TITLE
[HELP] Cannot get LAPS and BL

### ISSUE THREAD

**Issue by sonnenx** [lithnet/access-manager#147]
Hej,

When I request a LAPS password or Bitlocker key, I get:

![image](https://user-images.githubusercontent.com/37338780/157118594-48d10685-a61a-41f7-949d-21deb1cc2236.png)

![image](https://user-images.githubusercontent.com/37338780/157118615-c0c232e7-2529-4379-9caa-3a440bac15cc.png)

The machines have both in AD.

What should I check?

Best.

**Comment by ryannewington** [comment]
The AMS service account doesn't have permission to read that information from the directory. You can use the delegation scripts that can be generated from within the configuration app to correctly assign permissions.
