### ISSUE TITLE
How is the username of the local administrator account to be managed defined?

### ISSUE THREAD

**Issue by kyle0440** [lithnet/access-manager#150]
LAPS has the setting "Name of administrator account to manage" in its GPO, but the Lithnet Access Manager Agent does not. How is this setting supposed to be defined when using the access manager agent?

**Comment by ryannewington** [comment]
It looks for the built in administrator SID, which is well known and the same on every computer, therefore it doesn't need you to provide the account name.

**Comment by kyle0440** [comment]
So when migrating away from a LAPS install (which managed the password of a user that's _not_ the built-in Administrator account), I would need to 

- set up a GPO to enable the built-in Administrator account, and 
- switch to using that account for local admin instead?

**Comment by ryannewington** [comment]
Ah yes. Access manager only manages the built in admin account. So if it's a different account, not just one that's been renamed, we don't have support for that scenario. So as you said, reenable the built in admin and manage that instead.
