### ISSUE TITLE
Migrating service to another server

### ISSUE THREAD

**Issue by gizanopatrica** [lithnet/access-manager#152]
Hi,

Apologies if this is not the correct place for this sort of question

I have installed the Access Manager service onto a server, but am wondering what the procedure would be to migrate the service to another server in the future

Is it as simple as reinstalling the service on another server and then copying the configuration over? The installation package also downloads SQL Server so I am assuming that a database needs to be ported over in addition to this?

Would be helpful for this to be covered in the wiki or an FAQ section

Thanks in advance

**Comment by ryannewington** [comment]
@gizanopatrica you've come to the right place.

Yes, the procedure would be to 
1. Install AMS on the new server
2. Set up the SSL certificiate
3. Stop the service
4. copy the `config` folder from the old server
5. Restart the service

The database is used as a cache, and contains no stateful information, so you don't need to worry about the database.

Note that if you do not use the same service account, you will have to re-enter all the secrets/passwords in the UI app and resave them.

Do let me know if you need any more information
