### ISSUE TITLE
[HELP] Acess Denied

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#159]
### Access Denied
Hello,
basic setup with a Single Forest with multiple domains. Service used is a gMSA with proper delegations on requested OU.
Permission assigned correctly but in the log we receive
"System.UnauthorizedAccessException: Access is denied.".
Through web interface we receive "Unable to process request 
An error occurred while trying to access the local admin password".
Any help or suggestion greatly appreciated.
Regards,
Red.

**Comment by red-erik** [comment]
Solved: to help other the problem is that gMSA account NEEDS write access to AdmPwdExpirationTime to and not only read access to pwd attibutes. Analizing you script it is clear but I suggest to underline into instructions too.
https://github.com/lithnet/access-manager/wiki/Creating-a-service-account-for-the-Access-Manager-Service
Domain permissions
AMS does need specific rights depending on how you plan to use it. For example, if you are reading Microsoft LAPS passwords, then you'll need to ensure the appropriate read permissions are granted.

**Comment by milanbla** [comment]
Hi,
In my case, it said something like 'the computer does not have a password and in the log, I had errors :
_Unable to get password from provider 'Windows LAPS (encrypted) AD provider'
System.UnauthorizedAccessException: Access is denied._
This solution also helped me 👍
