### ISSUE TITLE
Installer incorrectly demands the specific version of .NET Core Desktop 3.1.4 and does not detect later versions

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#16]
Hello,
in "Installing Access Manager" the section "prerequisites" says:

    Windows Server 2012 R2 or later
    .NET Core Desktop Runtime 3.1.4 or later installed
    ASP.NET Core Hosting Bundle 3.1.4 or later installed
    An SSL certificate for the AMS web site

but if you try to install with  .NET Core Desktop Runtime 3.1.7 already installed, you receive an error saying that  .NET Core Desktop Runtime 3.1.4 is missing and required.
So, later versions seems to be unsupported.

Regards,

Red.

**Comment by ryannewington** [comment]
Thanks @red-erik we'll look into this.

@s881628 what version of .net core desktop did you deploy?

**Comment by ryannewington** [comment]
Confirmed to be a problem with the installers detection logic.

Issues has now been resolved and tested on a system with only 3.1.7 installed and confirmed working.

Thanks for the report @red-erik

**Comment by s881628** [comment]
@ryannewington  I can confirm that I am using 3.1.4 in my lab environment.   
I upgraded to 3.1.7 after AMS had been installed and can confirm that AMS is still working after the update.  Looks to be an installer dependency check causing the error.

**Comment by s881628** [comment]
Well I should have refreshed the page before posting... You beat me to it!

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.
