### ISSUE TITLE
Authentication issue 404

### ISSUE THREAD

**Issue by Afsars12** [lithnet/access-manager#162]
Hi Team

I have configured the Lithnet access manager as per the article, When it comes to Authentication I have selected open ID and updated client id and secret details obtained from Identity provider Okta.

the format of my redirect URI are below.

https://abc.test.local/auth/ (ABC is my host where i have installed lithnet access manager service)

Please let me know if it is correct, as I am following the below link. 
https://docs.lithnet.io/ams/configuration/setting_up_authentication/setting-up-authentication-with-okta

Regards
Afsar

**Comment by ryannewington** [comment]
Hi Afsar,

When do you get the 404 error appear?

**Comment by Afsars12** [comment]
> 

Hi Ryan

I have added the application in Okta and the lithnet access manager tile is appearing in my sso page, whenever I am clicking on the tile its giving me 404,

**Comment by ryannewington** [comment]
Hi Afsar,

The /auth endpoint is a special url for posting back an authorisation response after login. It is correct to use this as the sign in reply url, but it's not something you can navigate to as a user. 

Your okta tile for the end user should be configured to point to the application root 

eg https://abc.test.local/

Ryan

**Comment by Afsars12** [comment]
> Hi Afsar,
> 
> The /auth endpoint is a special url for posting back an authorisation response after login. It is correct to use this as the sign in reply url, but it's not something you can navigate to as a user.
> 
> Your okta tile for the end user should be configured to point to the application root
> 
> eg https://abc.test.local/
> 
> Ryan

Thanks Ryan, it helped
