### ISSUE TITLE
Couldnot find log format Documentation

### ISSUE THREAD

**Issue by collegenote** [lithnet/access-manager#167]
Hello there, I could not find the log format documentation. Let me know where could I get the documentation to know the log field?
Thanks

**Comment by ryannewington** [comment]
Hi @collegenote 

Can you elaborate a bit more on what you are looking to get from or do with the logs?

**Comment by collegenote** [comment]
I want to understand /extract log value to get complete picture what exactly the individual log mean.

**Comment by ryannewington** [comment]
If you are referring to the log file, then the format used to build the log entry is as follows

"${longdate}|${loglevel}|${loggername}|${message}${onexception:inner=${newline}${exceptionMessage}}"

If that's not what you are after, if you can include a log entry and tell me what you want to extract from it I might be able to be of more help.

**Comment by collegenote** [comment]
Thanks for the format but i am seeking for possible value and meaning of individual log's entry . For Instance  event id and its corresponding meaning if  those event id signified some things .

**Comment by ryannewington** [comment]
We don't have anything like that published, but the definitive list of event IDs, and a very basic description can be inferred from the internal name.

https://github.com/lithnet/access-manager/blob/master/src/Lithnet.AccessManager/Lithnet.AccessManager/EventIDs.cs

**Comment by collegenote** [comment]
thanks for help
