### ISSUE TITLE
Autorization rule never matching

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#17]
Hello,
I granted Authorization to a specific OU for a specific Group. My user is a member of the group but I'm not authorized to view LAPS password.
In the log I see (some line missing for privacy):

Access type:               None
Username:                  DOMAIN\red.erik
Name:                      Red Erik
UPN:                       red.erik@xxxxxx.yy
SID:                       S-1-5-21-2531055191-855916945-2278501704-9390
User DN:                   CN=aaaaaaaaa,OU=bbbbb,OU=ccccccc,DC=to,DC=xxxxxxx,DC=yy
Requestor IP:              10.152.32.3
Requestor Hostname:        
...
Matched rule:              
Matched rule description:  
AuthZ response:            NoMatchingRuleForUser
Detail:                    The user domain\red.erik is not authorized to access the computer dddddddddd.
Request reason:            (not provided)

Regards,

Red.

**Comment by ryannewington** [comment]
Would you be able to email the full [access-manager-service.log](https://github.com/lithnet/access-manager/wiki/Troubleshooting) to support@lithnet.io

**Comment by red-erik** [comment]
Done as requested.

Red.

**Comment by ryannewington** [comment]
Thanks. I take it the group in question is a domain local group like we had in the previous laps-web situation?

I've built a solution into this just for you, but it does require that you have at least one 2012 server (or better) in the target domain. It doesn't have to be a DC, just a member server is fine. We need to tell Access Manager to use that machine as our authorization server. To do this, on the local machine, add the access manager service account to the `Access Control Assistance Operators` local group on that computer.

Then, in the Access Manager server, open `C:\Program Files\Lithnet\Access Manager Service\config\appsettings.json` in a text editor.

Look for the `"Authorization":` node, and add in the following directly after `"Authorization":` and before `"ComputerTargets"`

```json
 "AuthorizationServerMapping": [
      {
        "Domain": "yourdomain.local",
        "Servers": [
          {
            "Name": "some2012server.idmdev1.local",
            "Type": "Default"
          }        
        ]
      }
    ],
```
So it will look like this

```json
"Authorization": {
    "AuthorizationServerMapping": [
      {
        "Domain": "yourdomain.local",
        "Servers": [
          {
            "Name": "some2012server.idmdev1.local",
            "Type": "Default"
          }        
        ]
      }
    ],
    "ComputerTargets": .......
```

You can use a tool like [jsonlint](https://jsonlint.com/) to make sure you have got the formatting correct.

Restart the AMS service and try again.

**Comment by ryannewington** [comment]
@red-erik how did you go?

**Comment by red-erik** [comment]
Hello,
still stuck on "AuthZ response:            NoMatchingRuleForUser"

Red.

**Comment by ryannewington** [comment]
Sorry to hear. Can you email through your updated appsettings.json file, and the most recent log file to support@lithnet.io and I'll see what is going on.

**Comment by red-erik** [comment]
Done as requested.

Red.

**Comment by red-erik** [comment]
Hello,
it seems that with you custom file I can access LAPS passwords on Root Domain machines but NOT on child domain. Do I need to add a Win2012 or + for every child domain in C:\Program Files\Lithnet\Access Manager Service\config\appsettings.json ?
If yes, witch is the correct syntax for multiple servers ?

Regards,

Red.

**Comment by red-erik** [comment]
Hello,
I confirm, adding something like:

"AuthorizationServerMapping": [
      {
        "Domain": "yourdomain.local",
        "Servers": [
          {
            "Name": "some2012server.yourdomain.local",
            "Type": "Default"
          }        
        ]
      },
 {
        "Domain": "child.yourdomain.local",
        "Servers": [
          {
            "Name": "some2012server.child.yourdomain.local",
            "Type": "Default"
          }        
        ]
      }
    ],

Regards,

Red.

**Comment by ryannewington** [comment]
Hi Red,

Yes that's right. Without having a 2012 or better domain controller, you'll need to designate a single 2012+ server in each domain to act as the authorization server. This is the server used to calculate the domain local group membership, so it can only do that, if it is a member of that domain.

The syntax you have looks correct. For each domain without a 2012 DC, you add in an additional domain section with an authorization server to use in its place.

Ryan

**Comment by red-erik** [comment]
Hello,
this is fine but the problem is that if I add and Auth Target in the AMS GUI  manager, I loose all my custom modification to the json...

Regards,

Red.

**Comment by ryannewington** [comment]
Sorry I should have called this one out before.

Just make sure you close the GUI before you edit the file. Make your edits, and save the file, and then go back in the GUI and you will not have your settings overwritten. 

This is because the GUI loads the file into memory when it is first opened. Whenever you save in the GUI, it is saving its in-memory copy back to the file. When you edit the file outside of the GUI, with the GUI still open, it doesn't check for your changes and just overwrites with the in-memory copy it has.

**Comment by red-erik** [comment]
Thank you, I'm closing the case.

Red.
