### ISSUE TITLE
[HELP] Problem with installation

### ISSUE THREAD

**Issue by ksmosna** [lithnet/access-manager#170]
Hello,
I am trying to install AMS, but the problem is that the installation ends with the message "Lithnet Access Manager Service setup ended prematurely because of an error...".

I have nothing in the logs folder. Where can I look for what's the problem?

**Comment by ryannewington** [comment]
@ksmosna 
From an elevated command prompt, you can run the installer with the following parameters to generate the log
`Lithnet.AccessManager.Service.Setup.exe /l*v C:\install.log`

Feel free to post the log here if you need a hand understanding the error that is logged

**Comment by ksmosna** [comment]
In logs I can see that I do not meet one requirement - SQL Server 2019 (currently I have an instance of 2017). Could that be it? Below I am sending the last part of the log file.

`AddServicePermissionsToRegistryKey $certStoreRegKey "FullControl"
CreateServiceRegistryKey $regKey

Property(S): AI_SETUPEXEPATH_ORIGINAL = c:\Lithnet.AccessManager.Service.Setup.exe
Property(S): ARPINSTALLLOCATION = C:\Program Files\Lithnet\Access Manager Service\
Property(S): AMS_ADMINS_SID = S-1-5-21-529171235-3400179608-3813816412-3714
Property(S): SourceDir = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): bootstrap_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\bootstrap\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): runtimes_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\
Property(S): win_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\
Property(S): lib_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\
Property(S): net6.0_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\net6.0\
Property(S): Modules_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\net6.0\Modules\
Property(S): fontawesome_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\font-awesome\
Property(S): lib_1_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\
Property(S): VersionNT = 1000
Property(S): RedirectedDllSupport = 2
Property(S): PackageCode = {01328A77-A05C-44C8-A183-B7989FEB0417}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): USERNAME = Użytkownik systemu Windows
Property(S): VersionDatabase = 200
Property(S): AIEXTERNALUI = 5
Property(S): REMOVE = SQLExpress2017
Property(S): ACTION = INSTALL
Property(S): AI_MORE_CMD_LINE = 1
Property(S): CHAINERUIPROCESSID = 6040Chainer
Property(S): CLIENTPROCESSID = 7128
Property(S): SECONDSEQUENCE = 1
Property(S): EXECUTEACTION = INSTALL
Property(S): CLIENTUILEVEL = 0
Property(S): ADDLOCAL = MainFeature,ConfigurationFilesFeature
Property(S): AI_FOUND_PREREQS = ASP.NET Runtime 6.0 x64|.NET Desktop Runtime 6.0 x64|SQL Express 2017|SQL Express 2019
Property(S): PRIMARYFOLDER = APPDIR
Property(S): ROOTDRIVE = C:\
Property(S): AI_PREREQDIRS = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service\prerequisites
Property(S): SETUPEXEDIR = c:\
Property(S): EXE_CMD_LINE = /exenoupdates  /forcecleanup  /wintime 1662117449 /l*v C:\install.log 
Property(S): MsiSystemRebootPending = 1
Property(S): VersionMsi = 5.00
Property(S): VersionNT64 = 1000
Property(S): WindowsBuild = 20348
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 2
Property(S): WindowsFolder = C:\Windows\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\ADMINI~1.GAL\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\Administrator.GALMET\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\Administrator.GALMET\Favorites\
Property(S): NetHoodFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\Administrator.GALMET\Documents\
Property(S): PrintHoodFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\Administrator.GALMET\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\Administrator.GALMET\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 8191
Property(S): VirtualMemory = 7531
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
Property(S): LogonUser = Administrator
Property(S): UserSID = S-1-5-21-529171235-3400179608-3813816412-500
Property(S): UserLanguageID = 1045
Property(S): ComputerName = AD-CONTROLLER3
Property(S): SystemLanguageID = 1045
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 19
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 06:10:22
Property(S): Date = 05.09.2022
Property(S): MsiNetAssemblySupport = 4.8.4161.0
Property(S): MsiWin32AssemblySupport = 6.3.20348.825
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): DATABASE = C:\Windows\Installer\deb1133.msi
Property(S): OriginalDatabase = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\Lithnet.AccessManager.Service.Setup.msi
Property(S): UILevel = 5
Property(S): Preselected = 1
Property(S): SavedGamesFolder = C:\Users\Administrator.GALMET\Saved Games\
Property(S): WindowsLibrariesFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Libraries\
Property(S): PublicDocumentsFolder = C:\Users\Public\Documents\
Property(S): PublicFolder = C:\Users\Public\
Property(S): UserProfileFolder = C:\Users\Administrator.GALMET\
Property(S): IS_AMS_SERVICE_NOT_INSTALLED = 1
Property(S): IS_STANDALONE = 1
Property(S): IS_STANDALONE_OR_NOT_CLUSTERED_OR_ON_ACTIVE_NODE = 1
Property(S): POWERSHELL_EXECUTION_LOG = ERROR: Exception calling "SetAccessRule" with "1" argument(s): "Nie można przetłumaczyć niektórych lub żadnych odwołań do tożsamości."
Property(S): CAN_SKIP_DIALOGSAiVerMin = 1.12.8052
Property(S): CostingComplete = 1
Property(S): OutOfDiskSpace = 0
Property(S): OutOfNoRbDiskSpace = 0
Property(S): PrimaryVolumeSpaceAvailable = 207112480
Property(S): PrimaryVolumeSpaceRequired = 375312
Property(S): PrimaryVolumeSpaceRemaining = 206737168
Property(S): PrimaryVolumePath = C:
Property(S): SOURCEDIR = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\
Property(S): SourcedirProduct = {28403863-ACE8-4C5E-9BCF-0A0B2BB6B524}
Property(S): ProductToBeRegistered = 1
MSI (s) (2C:38) [06:10:22:171]: MainEngineThread is returning 1603
MSI (s) (2C:F0) [06:10:22:182]: RESTART MANAGER: Session closed.
MSI (s) (2C:F0) [06:10:22:182]: No System Restore sequence number for this installation.
MSI (s) (2C:F0) [06:10:22:187]: User policy value 'DisableRollback' is 0
MSI (s) (2C:F0) [06:10:22:187]: Machine policy value 'DisableRollback' is 0
MSI (s) (2C:F0) [06:10:22:187]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (2C:F0) [06:10:22:187]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (2C:F0) [06:10:22:187]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (2C:F0) [06:10:22:187]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (2C:F0) [06:10:22:202]: Destroying RemoteAPI object.
MSI (s) (2C:68) [06:10:22:202]: Custom Action Manager thread ending.
MSI (c) (D8:6C) [06:10:22:202]: Back from server. Return value: 1603
MSI (c) (D8:6C) [06:10:22:202]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (D8:6C) [06:10:22:202]: PROPERTY CHANGE: Deleting SECONDSEQUENCE property. Its current value is '1'.
Action ended 06:10:22: ExecuteAction. Return value 3.
=== Verbose logging stopped: 2022-09-05  06:10:22 ===

MSI (c) (98:14) [06:09:15:979]: PROPERTY CHANGE: Modifying AI_FOUND_PREREQS property. Its current value is 'ASP.NET Runtime 6.0 x64|.NET Desktop Runtime 6.0 x64'. Its new value: 'ASP.NET Runtime 6.0 x64|.NET Desktop Runtime 6.0 x64|SQL Express 2017|SQL Express 2019'.
MSI (c) (98:14) [06:09:15:979]: Note: 1: 2205 2:  3: AI_TempFile 
MSI (c) (98:14) [06:09:15:979]: Note: 1: 2228 2:  3: AI_TempFile 4: SELECT `Property` FROM `AI_TempFile` 
MSI (c) (98:14) [06:09:15:979]: Note: 1: 2205 2:  3: AI_XmlLocator 
MSI (c) (98:14) [06:09:15:979]: Note: 1: 2228 2:  3: AI_XmlLocator 4: SELECT `Property` FROM `AI_XmlLocator` 
MSI (c) (98:14) [06:09:17:345]: Note: 1: 2205 2:  3: AI_ChainedPackage 
MSI (c) (98:14) [06:09:17:345]: Note: 1: 2228 2:  3: AI_ChainedPackage 4: SELECT `ChainedPackage` FROM `AI_ChainedPackage` 
MSI (c) (98:14) [06:10:22:202]: Doing action: FatalError
Action start 06:10:22: FatalError.
Action ended 06:10:27: FatalError. Return value 1.
MSI (c) (98:14) [06:10:27:285]: Doing action: AI_SHOW_LOG
Action start 06:10:27: AI_SHOW_LOG.
MSI (c) (98:D4) [06:10:27:380]: Invoking remote custom action. DLL: C:\Users\ADMINI~1.GAL\AppData\Local\Temp\MSI1DF2.tmp, Entrypoint: LaunchLogFile
Action ended 06:10:27: AI_SHOW_LOG. Return value 1.
MSI (c) (98:14) [06:10:27:603]: Doing action: FatalError
Action start 06:10:27: FatalError.
Action ended 06:10:27: FatalError. Return value 1.
MSI (c) (98:14) [06:10:27:603]: Doing action: AI_AiBackupCleanup
Action start 06:10:27: AI_AiBackupCleanup.
MSI (c) (98:B8) [06:10:27:697]: Invoking remote custom action. DLL: C:\Users\ADMINI~1.GAL\AppData\Local\Temp\MSI1F2B.tmp, Entrypoint: OnAiBackupCleanup
Action ended 06:10:28: AI_AiBackupCleanup. Return value 1.
MSI (c) (98:14) [06:10:28:608]: Doing action: FatalError
Action start 06:10:28: FatalError.
Action ended 06:10:28: FatalError. Return value 1.
MSI (c) (98:14) [06:10:28:608]: Doing action: AI_CleanPrereq
Action start 06:10:28: AI_CleanPrereq.
MSI (c) (98:FC) [06:10:28:686]: Invoking remote custom action. DLL: C:\Users\ADMINI~1.GAL\AppData\Local\Temp\MSI2314.tmp, Entrypoint: CleanPrereq
Action ended 06:10:28: AI_CleanPrereq. Return value 1.
MSI (c) (98:14) [06:10:28:892]: Doing action: FatalError
Action start 06:10:28: FatalError.
Action ended 06:10:28: FatalError. Return value 2.
MSI (c) (98:14) [06:10:28:901]: Note: 1: 2205 2:  3: Environment 
MSI (c) (98:14) [06:10:28:901]: Note: 1: 2228 2:  3: Environment 4: SELECT `Environment`,`Component_` FROM `Environment` 
MSI (c) (98:14) [06:10:28:955]: Destroying RemoteAPI object.
MSI (c) (98:A4) [06:10:28:955]: Custom Action Manager thread ending.
=== Verbose logging stopped: 2022-09-05  06:10:28 ===

`

**Comment by ksmosna** [comment]
here it is log when i am trying to install AMS with SQL 2019 that is included to installer.

`Property(S): AI_SETUPEXEPATH_ORIGINAL = c:\Lithnet.AccessManager.Service.Setup.exe
Property(S): ARPINSTALLLOCATION = C:\Program Files\Lithnet\Access Manager Service\
Property(S): AMS_ADMINS_SID = S-1-5-21-529171235-3400179608-3813816412-3714
Property(S): SourceDir = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): bootstrap_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\bootstrap\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): runtimes_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\
Property(S): win_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\
Property(S): lib_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\
Property(S): net6.0_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\net6.0\
Property(S): Modules_Dir = C:\Program Files\Lithnet\Access Manager Service\runtimes\win\lib\net6.0\Modules\
Property(S): fontawesome_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\font-awesome\
Property(S): lib_1_Dir = C:\Program Files\Lithnet\Access Manager Service\wwwroot\lib\
Property(S): VersionNT = 1000
Property(S): RedirectedDllSupport = 2
Property(S): PreReqSearch_1_1 = 1
Property(S): SQLEXPRESS_INSTANCE_EXISTS = 1
Property(S): PackageCode = {01328A77-A05C-44C8-A183-B7989FEB0417}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): USERNAME = Użytkownik systemu Windows
Property(S): VersionDatabase = 200
Property(S): AIEXTERNALUI = 5
Property(S): AI_MORE_CMD_LINE = 1
Property(S): ACTION = INSTALL
Property(S): AI_MISSING_PREREQS = SQL Express 2019
Property(S): CHAINERUIPROCESSID = 4260Chainer
Property(S): CLIENTPROCESSID = 6112
Property(S): SECONDSEQUENCE = 1
Property(S): EXECUTEACTION = INSTALL
Property(S): CLIENTUILEVEL = 0
Property(S): ADDLOCAL = MainFeature,ConfigurationFilesFeature,SQLExpress2017
Property(S): AI_FOUND_PREREQS = ASP.NET Runtime 6.0 x64|.NET Desktop Runtime 6.0 x64|SQL Express 2017
Property(S): PRIMARYFOLDER = APPDIR
Property(S): ROOTDRIVE = C:\
Property(S): AI_PREREQFILES = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service\prerequisites\SQLExpress2017\SQLEXPR_x64_ENU.exe
Property(S): AI_PREREQDIRS = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service\prerequisites
Property(S): SETUPEXEDIR = c:\
Property(S): EXE_CMD_LINE = /exenoupdates  /forcecleanup  /wintime 1662117449 /l*v C:\install.log 
Property(S): VersionMsi = 5.00
Property(S): VersionNT64 = 1000
Property(S): WindowsBuild = 20348
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 2
Property(S): WindowsFolder = C:\Windows\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\ADMINI~1.GAL\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\Administrator.GALMET\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\Administrator.GALMET\Favorites\
Property(S): NetHoodFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\Administrator.GALMET\Documents\
Property(S): PrintHoodFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\Administrator.GALMET\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\Administrator.GALMET\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 8191
Property(S): VirtualMemory = 7063
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
Property(S): LogonUser = Administrator
Property(S): UserSID = S-1-5-21-529171235-3400179608-3813816412-500
Property(S): UserLanguageID = 1045
Property(S): ComputerName = AD-CONTROLLER3
Property(S): SystemLanguageID = 1045
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 19
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 06:57:29
Property(S): Date = 05.09.2022
Property(S): MsiNetAssemblySupport = 4.8.4161.0
Property(S): MsiWin32AssemblySupport = 6.3.20348.825
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): DATABASE = C:\Windows\Installer\e0fc603.msi
Property(S): OriginalDatabase = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\Lithnet.AccessManager.Service.Setup.msi
Property(S): UILevel = 5
Property(S): Preselected = 1
Property(S): SavedGamesFolder = C:\Users\Administrator.GALMET\Saved Games\
Property(S): WindowsLibrariesFolder = C:\Users\Administrator.GALMET\AppData\Roaming\Microsoft\Windows\Libraries\
Property(S): PublicDocumentsFolder = C:\Users\Public\Documents\
Property(S): PublicFolder = C:\Users\Public\
Property(S): UserProfileFolder = C:\Users\Administrator.GALMET\
Property(S): IS_AMS_SERVICE_NOT_INSTALLED = 1
Property(S): IS_STANDALONE = 1
Property(S): IS_STANDALONE_OR_NOT_CLUSTERED_OR_ON_ACTIVE_NODE = 1
Property(S): POWERSHELL_EXECUTION_LOG = ERROR: Exception calling "SetAccessRule" with "1" argument(s): "Nie można przetłumaczyć niektórych lub żadnych odwołań do tożsamości."
Property(S): CAN_SKIP_DIALOGSAiVerMin = 1.12.8052
Property(S): CostingComplete = 1
Property(S): OutOfDiskSpace = 0
Property(S): OutOfNoRbDiskSpace = 0
Property(S): PrimaryVolumeSpaceAvailable = 204245384
Property(S): PrimaryVolumeSpaceRequired = 375314
Property(S): PrimaryVolumeSpaceRemaining = 203870070
Property(S): PrimaryVolumePath = C:
Property(S): SOURCEDIR = C:\Users\Administrator.GALMET\AppData\Roaming\Lithnet\Lithnet Access Manager Service 2.0.8904.0\install\BB6B524\
Property(S): SourcedirProduct = {28403863-ACE8-4C5E-9BCF-0A0B2BB6B524}
Property(S): ProductToBeRegistered = 1
MSI (s) (F0:40) [06:57:30:025]: MainEngineThread is returning 1603
MSI (s) (F0:14) [06:57:30:025]: RESTART MANAGER: Session closed.
MSI (s) (F0:14) [06:57:30:025]: No System Restore sequence number for this installation.
MSI (s) (F0:14) [06:57:30:041]: User policy value 'DisableRollback' is 0
MSI (s) (F0:14) [06:57:30:041]: Machine policy value 'DisableRollback' is 0
MSI (s) (F0:14) [06:57:30:041]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (F0:14) [06:57:30:041]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F0:14) [06:57:30:041]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F0:14) [06:57:30:041]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (F0:14) [06:57:30:057]: Destroying RemoteAPI object.
MSI (s) (F0:EC) [06:57:30:057]: Custom Action Manager thread ending.
MSI (c) (E0:A4) [06:57:30:057]: Back from server. Return value: 1603
MSI (c) (E0:A4) [06:57:30:057]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (E0:A4) [06:57:30:057]: PROPERTY CHANGE: Deleting SECONDSEQUENCE property. Its current value is '1'.
Action ended 06:57:30: ExecuteAction. Return value 3.
=== Verbose logging stopped: 2022-09-05  06:57:30 ===

MSI (c) (A4:94) [06:56:24:525]: Note: 1: 2205 2:  3: AI_TempFile 
MSI (c) (A4:94) [06:56:24:525]: Note: 1: 2228 2:  3: AI_TempFile 4: SELECT `Property` FROM `AI_TempFile` 
MSI (c) (A4:94) [06:56:24:525]: Note: 1: 2205 2:  3: AI_XmlLocator 
MSI (c) (A4:94) [06:56:24:525]: Note: 1: 2228 2:  3: AI_XmlLocator 4: SELECT `Property` FROM `AI_XmlLocator` 
MSI (c) (A4:94) [06:56:24:603]: Note: 1: 2205 2:  3: AI_ChainedPackage 
MSI (c) (A4:94) [06:56:24:603]: Note: 1: 2228 2:  3: AI_ChainedPackage 4: SELECT `ChainedPackage` FROM `AI_ChainedPackage` 
MSI (c) (A4:94) [06:57:30:057]: Doing action: FatalError
Action start 06:57:30: FatalError.`

**Comment by ryannewington** [comment]
@ksmosna 

I'll need to see the whole log. can you email it to support@lithnet.io
