### ISSUE TITLE
Unable to Update Hostname

### ISSUE THREAD

**Issue by afscme-kmchugh** [lithnet/access-manager#174]
After upgrading to V 2.0.9 the ability to update the Hostname is missing in the GUI and modifying the registry keys to a new hostname causes the app to fail.

**Comment by ryannewington** [comment]
@afscme-kmchugh 

The ability to modify the hostname was removed in v2, but after modifying the registry as you did, you can update the URL reservations like so.  Run the following commands from an elevated command prompt, and replace 'host' with your new host name.

```
netsh http delete urlacl http://+:80/
netsh http delete urlacl http://+:443/
netsh http delete urlacl http://+:443/api/v1.0

netsh http add urlacl url= http://host:80/ listen= yes user= "NT Service\lithnetams"
netsh http add urlacl url= http://host:443/ listen= yes user= "NT Service\lithnetams"
netsh http add urlacl url= http://host:443/api/v1.0 listen= yes user= "NT Service\lithnetams"

```

If the registry settings and the URL reservations match, you should be able to start the service.
