### ISSUE TITLE
2FA access on the website by using either Authenticator or FIDO2 usb keys)

### ISSUE THREAD

**Issue by dxdemetriou** [lithnet/access-manager#175]
**Is your feature request related to a problem? Please describe.**
-  It could be useful to have a 2FA authentication on login either by some Authenticator or some usb FIDO2 key.

**Describe the solution you'd like**
- Supporting 2FA on login that each user using the website could be able to configure their own.

**Comment by ryannewington** [comment]
@dxdemetriou 

Thanks for the suggestion. Our strategy for delivering MFA support is by delegating authentication to an external provider such as Azure AD or Okta. Authentication is complex to implement, and every customer has different requirements so we've opted to provide the most flexible option, which is delegating to external providers.

More information can be found in our guide.

https://docs.lithnet.io/ams/v/1.0/configuration/setting_up_authentication/setting-up-authentication-with-azure-ad

Ryan
