### ISSUE TITLE
Unable to find database after upgrading from 1.0.7941.0 to 2.0.8904

### ISSUE THREAD

**Issue by davyyd** [lithnet/access-manager#176]
**Describe the bug**
After completing the installation of Lithnet Access Manager Service (version 2.0.8904) over an existing installation of version 1.0.794, the Lithnet Access Manager service does not start.

**To Reproduce**
 Install version 2.0.8904 over version 1.0.794
    Select the option to use a local installation of SQL Lite
Check the Windows Services control panel, and attempt to start "Lithnet Access Manager Service"
Note that access-manager-service.log reports "The database could not be found"

**Expected behavior**
Expected the service to start and stay running

**Screenshots**

**Access Manager installation**
 - OS: Windows Server 2019 Standard
 - Version 2.0.8904

**Logs**
[access-manager-service.log](https://github.com/lithnet/access-manager/files/9609556/access-manager-service.log)

**Comment by ryannewington** [comment]
@davyyd 

Thank you for reporting this. We're able to reproduce the issue using the conditions you described. There looks to be a bug in the installer. We will investigate further and let you know the results.

Ryan
