### ISSUE TITLE
.net Core 3.1 reaches End of Support 13th December 2022

### ISSUE THREAD

**Issue by padlock780** [lithnet/access-manager#177]
I have tried using Lithnet Access Manager Service with **Microsoft Windows Desktop Runtime - 6.09 (x64)** and **Microsoft ASP.NET Core 6.0.9 - Shared Framework (x64)**. In order to mirror the 3.1.14 versions the installer downloads. However the **Lithnet Access Manager Service** will no longer start. Is there work to release an update to support the use of dot net core 6.0.x ?

**Comment by ryannewington** [comment]
@padlock780 

Yes, a dotnet 6.0 version of AMS v1 will be released before the 3.1 EOL. v2 is already using dotnet 6
