### ISSUE TITLE
Active Directory "Microsoft LAPS Schema" check failing

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#18]
Hello,
AMS detect "Microsoft LAPS Schema" as **NOT** present in the forest root while is obviously present (using it from a long time)
and obviously present in all child domains.

Regards,

Red.

**Comment by ryannewington** [comment]
Hi @red-erik ,

Could you send the [access-manager-ui.log](https://github.com/lithnet/access-manager/wiki/Troubleshooting) file to support@lithnet.io for this one

**Comment by red-erik** [comment]
Done as requested.

Red.

**Comment by ryannewington** [comment]
Found and fixed this issue. It will be in the next build.

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.
