### ISSUE TITLE
Azure AD auth issues. OpenID

### ISSUE THREAD

**Issue by Chesedro** [lithnet/access-manager#190]
### Subject of the issue
Trying to setup Access Manager web to auth to Azure AD. Setup seems pretty straightforward, however the line in the instruction for "issuer/Authority" seems it should be something more like "https://login.microsoftonline.com/TenantID" but this does not work. It seems what ever I add into this field and then save it. The AM Web portal won't load at all. I then move it back to "integrated Windows Auth" and the Page loads just fine. So My two questions are. Am I using the correct "issuer/Authority" and or am I missing something on the server hosting the web portal that is needed for OpenID to work properly? 

Also Note: that if you open Azure ad and go to the newly created App registration. Click "Endpoints" there is a dedicated endpoint for "OpenID"  I have tried this one too with he same result. no luck. 

Thanks for all your help

T

**Comment by ryannewington** [comment]
@Chesedro 

Here's the screen shot of a working setup
![image](https://user-images.githubusercontent.com/17229877/203403006-c6074267-2a18-4cd5-8352-6e99a161b35f.png)

What version of AMS are you running?

You should be able to find more information in the log files at c:\Program Files\Lithnet\Access Manger Service\logs for specific details on what is failing.

**Comment by Chesedro** [comment]
Thanks for getting back to me. I feel stupid now. I did add that just as you posted and right away I got the login and was able to log in via Azure. I thought I had tried that the first time with no luck.. guess I was dreaming.  Thanks so much for your time. 

T

**Comment by ryannewington** [comment]
No problem! Glad it all working!
