### ISSUE TITLE
gMSA password incorrect,

### ISSUE THREAD

**Issue by Chesedro** [lithnet/access-manager#193]
gMSA password incorrect,

Working an issue. That for some reason I can run AMS with a Domain account no problem. But when I try to change the account to a gMAS the web portal no longer works. Once I authenticate the page wont load. I see an “Error 500”. Looking in the access-manager-service.log  and the access-manager-webapp.log  I see the same error below.

Lithnet.AccessManager.Enterprise.AmsLicenseManager|Unable to initialize forest information
System.Security.Authentication.AuthenticationException: The user name or password is incorrect.
 ---> System.Runtime.InteropServices.COMException (0x8007052E): The user name or password is incorrect.

At first I thought it was an issue with the gMSA account. And it may be. Tested with test-adserviceaccount result is “True” also made sure the property for “PrincipalsAllowedToRetrieveManagedPassword” is set for the hostname properly. Clearly since I got the “True” result in test-adserviceaccount.  
The lithnetams service does start with no errors.  Also Everything in AMS configuration tool looks good. No errors all green checkmarks where needed. 

I have removed and recreated the gMSA account several times with the same result. Each time I can get the site back up working only if I use a standard AD account. 
I have been using the ps script provided to create the gMSA. Unrelated, I get an error adding the gMSA with the script provided saying its missing the -path parameter. Adding this however, resolves the error. 

Any direction would be appreciated.. 

Thanks
T

**Comment by ryannewington** [comment]
@Chesedro 

This is a known symptom of the faulty November 2022 Windows Update

https://docs.lithnet.io/ams/help-and-support/support-articles/kb000005

**Comment by Chesedro** [comment]
Thanks ryannewington,  I am working on getting a window to apply these updates. till then I can leave AWS using a domain account. Thanks for getting back to me so quickly on this. 

T
