### ISSUE TITLE
Changing SQL Database

### ISSUE THREAD

**Issue by neojames** [lithnet/access-manager#196]
Hi,

We are currently upgrading the SQL server we are using in our test environment to a higher version. As part of this we intend to lift and shift the databases to the new instance, so we will need to re-point the server to the new SQL server IP. I cant find an option to do this in the GUI, is this something that is possible?

Thanks.

**Comment by ryannewington** [comment]
Hi @neojames 

What version of access manger are you using?

**Comment by neojames** [comment]
Hi @ryannewington,

I am using version 2.0.9339.0

**Comment by ryannewington** [comment]
Hi @neojames 

You can refer to this document for guidance

https://docs.lithnet.io/ams/help-and-support/support-articles/kb000006
