### ISSUE TITLE
Support for new LAPS schema and attributes introduced by latest MS updates

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#199]
Hello,
when new LAPS from MS will be fully supported ?
[https://techcommunity.microsoft.com/t5/windows-it-pro-blog/by-popular-demand-windows-laps-available-now/ba-p/3788747](url)
Thank you in advance for your great work.

Regards,
Red.

**Comment by ryannewington** [comment]
Hi @red-erik 

It's already supported! You just need to be on [2.0.9420](https://packages.lithnet.io/win/access-manager-service/v2.0/x64/LithnetAccessManagerService-2.0.9420.0-x64.exe).

**Comment by red-erik** [comment]
Thank you very much.
Regards,
Red.
