### ISSUE TITLE
LAPS/Bitlocker History

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#2]
One of the big problems with LAPS is that it's a field in AD that doesn't contain the history. Normally it isn't a problem until you revert to a snapshot of Virtual Machine or restore from a backup. You then lose the ability to login via AD (as trust is broken) but you also have LAPS key in AD that is no longer working. 

This makes it really tricky because you then need to reset the local password to login which may be a long process if you have BitLocker encrypted machines.

It's an even bigger problem if you have to restore AD (ransomware is big hit last few years) where you pick a backup from 2 months back and suddenly 90% of computers needs to be rebuilt because you don't have their BitLocker nor LAPS passwords (assuming they were not ransomwared).

The idea here is - do a daily or hourly backup of LAPS/Bitlocker fields into SQL DB (encrypted I guess) of things that change and keep it safe.

**Comment by ryannewington** [comment]
Already ahead of you on this one -> check out https://github.com/lithnet/access-manager/wiki/Getting-started-with-the-Lithnet-Access-Manager-Agent

**Comment by ryannewington** [comment]
and to stop you getting ransomwared in the first place -> https://github.com/lithnet/access-manager/wiki/Jit-Access-Page

So this version will contain
- Local admin password
- Local admin password history
- Just-in-time access

and we will add bitlocker before release

**Comment by PrzemyslawKlys** [comment]
This is so awesome!

**Comment by sylwester-majcher** [comment]
Hi, perfect one really!
About laps passwords and bitlocker keys history I personally doing it by ad snapschot by adexplorer based on cli of adexplorer. Than you can open snapschot offline

**Comment by PrzemyslawKlys** [comment]
Problem with history is that it needs to be stored in "secure place". AD is Tier 0. Storing ad snapshots somewhere safe and out of ransomware is another story.

**Comment by sylwester-majcher** [comment]
Yeah for sure. I also wait for new version of the tool. It looks it will be beautifull application!
About storing backup of laps or bitlocker pwd I also hve used „ntdsutil” tool to make an ad snapshot and next „dsamain” to moint on specific port to be able to attach by adsedit or aduc.
Best regards
And see you new version of Access Manager
