### ISSUE TITLE
OIDC claim unexpected error ISAM

### ISSUE THREAD

**Issue by janssen-bart** [lithnet/access-manager#202]
**Describe the bug**
We configured AMS to use ISAM via Oidc. Modified the claim name by override parameter on DB. When I restart the AMS service The first person can login. When a second person try's it drops unexpected error. 
After restart of the service one user is able to connect. 

**To Reproduce**
Setup ISAM via Oidc
override claimname
Login person 1 ok
Login person 2 NOK
Restart service
Login person 2 OK
Login person 1 NOK
restart...
...

**Expected behavior**
I expect multiple people can log in ;-)

**Access Manager installation**
 - OS: Windows Server 2019 17763.4252
 - Version 2.0.9420.0

**Comment by ryannewington** [comment]
Can you provide the access-manager-webapp.log from a reproduction of the issue?
