### ISSUE TITLE
Uninstall Lithnet AMS

### ISSUE THREAD

**Issue by dnauman1** [lithnet/access-manager#205]
When changing the authentication method, it caused the service to not start again. Uninstalling and re-installing AMS is asking for the master key password but it was never generated due to it being a test server. How can I completely remove AMS and start a fresh install without needing the master key password? Removing from add/remove programs and re-installing keeps asking for the master key password. UI log shows WARN|Lithnet.AccessManager.Server.UI.MainWindowViewModel|The service is currently in master key recovery mode

**Comment by ryannewington** [comment]
@dnauman1 The issue will be that the database still exists and is getting reattached each time.

If you download SQL management studio, you can connect to the .\AMS instance and delete the Access manager DB.

**Comment by dnauman1** [comment]
Thanks. That worked.
