### ISSUE TITLE
Can the numbers, uppercase letters, lowercase letters, and special characters in the password be marked with different colors?

### ISSUE THREAD

**Issue by mengdahuang** [lithnet/access-manager#210]
Hello，
Can the numbers, uppercase letters, lowercase letters, and special characters in the password be marked with different colors?

thanks

**Comment by ryannewington** [comment]
Letters, numbers and symbols are all in different colours. Lower and upper characters are not, but we use a specific font that clearly distinguishes between similar letters (upper case I and lower case L for example).

**Comment by mengdahuang** [comment]
thank you for your quickly reply.

could you please tell me how to change the fonts by user self? In fact, I came from another project of yours called "laps-web." I've been running that project smoothly for several years. I just want to make the differentiation between uppercase and lowercase letters a bit clearer.

Could you help me make uppercase and lowercase letters appear in different colors, or allow me to change the font to something more distinguishable? Thank you very much for your time and this wonderful tool.

**Comment by ryannewington** [comment]
Unfortunately it's not a user customisable option to change it. We'd have to look at adding an option in a future version.

**Comment by mengdahuang** [comment]
all right,

I've tried to change the source code, add `password-char-upper` and `password-char-lower` However, it seems that this 'control' directory and configuration file haven't been invoked. I'm wondering if I need to republish it using Visual Studio?

![image](https://github.com/lithnet/access-manager/assets/32334062/83c9d183-9511-47df-923f-cff24677e55c)

![image](https://github.com/lithnet/access-manager/assets/32334062/d3d2adc8-3dce-49ed-a3ae-1c80f21f4edd)


 thank you so much.

**Comment by mengdahuang** [comment]
closed
