### ISSUE TITLE
Add autocomplete/search and multi-select for computer JIT?

### ISSUE THREAD

**Issue by c3rberus** [lithnet/access-manager#214]
First off, this is an amazing tool and seamless to implement - wish I knew about this before... thanks for all your hard work in making this available to the community!

As we ramp up our usage of the identity management web interface, one feature request I think would be great to have some sort of autocomplete (or search) function and the ability to multi-select a group of computers for JIT.

Right now, you have to type the full computer name you are requesting access to, it would certainly save a few steps in having to go look for the exact computer name in other tools like ADUC.

**Comment by ryannewington** [comment]
Thanks for the kind feedback @c3rberus 

We've got some UI improvement ideas for a future release, and these are both suggestions we're definitely considering.

**Comment by c3rberus** [comment]
Good to know it's being considered for a future release, thanks!
