### ISSUE TITLE
Remove Expired Licence warning from Web Interface

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#216]
Hello,
we are testing the product and now the enterprise license is expired and the product is running as "Community Edition".
Fot our test is fine but it would be nice the remove the warnig from the Web interface.

Regards,
Red.

**Comment by jcspencer** [comment]
Hi @red-erik,

If you head to the [licence tab](https://docs.lithnet.io/ams/help-and-support/app-pages/licensing-page) and click _remove existing license_, this warning should disappear.

Let me know if this works for you!

**Comment by red-erik** [comment]
Hello,
in my release it is greyed out so I can't do anything.
![Access_Manager](https://github.com/lithnet/access-manager/assets/10245160/d0829e77-b2a6-426b-bc18-93b39aa1e9a0)

Regards,
Red.

**Comment by jcspencer** [comment]
Hi Red,

The particular version of AMS you have installed (v2.0.8904.0) has a built-in beta testing licence that is baked in to the installation. This cannot be removed like an enterprise edition licence.

Installing the latest version from [our AMS downloads page](https://lithnet.io/products/access-manager/downloads) will resolve this issue.

Regards,
James

**Comment by red-erik** [comment]
Hello,
it works, thank you very much.
