### ISSUE TITLE
Just in Time don't create Groups

### ISSUE THREAD

**Issue by r-edv** [lithnet/access-manager#217]
Hi
I have configured just-in-time access and activated automatic group creation but no groups are created. The service user has authorization to the OU. In the log I see this error: Lithnet.AccessManager.ConfigurationException: A JIT group mapping contains a null GroupOU field.
[access-manager-jit-workerold.log](https://github.com/lithnet/access-manager/files/12560276/access-manager-jit-workerold.log)

[access-manager-service.log](https://github.com/lithnet/access-manager/files/12572996/access-manager-service.log)
Thanks

**Comment by jcspencer** [comment]
Hi @r-edv, could you please include a copy of the "Automatic JIT access group creation" section of the  "Just-in-time access configuration" tab in the UI?

See [here](https://docs.lithnet.io/ams/help-and-support/app-pages/jit-access-page) for more information.

**Comment by r-edv** [comment]
Hi 
Reinstalling Sql + Lithnet Acces Manager resolve the issue.
Thanks
