### ISSUE TITLE
[Feature Request] Admin Approval for JIT Access

### ISSUE THREAD

**Issue by PhiZ-9** [lithnet/access-manager#220]
Hello,

I wanted to ask if a feature like "Admin Approval" from #123 is still being considered.
It would be great to have an admin approval process configurable for certain JIT Roles, where for example an email gets send out to a group of admins that have to "approve" or "deny" a request.

Since the last question / response on this topic is from 2021, I just wanted to ask if there is an update on this.

Thanks in advance!

**Comment by ryannewington** [comment]
@PhiZ-9 

No updates on this I'm afraid. We haven't discounted building it, but it's not currently on the roadmap.
