### ISSUE TITLE
JIT for Roles

### ISSUE THREAD

**Issue by TheImpossible21** [lithnet/access-manager#226]
Hi,

Trying to use the "Role Authorization rules" with the Domain Admin account, to enable timed access to as a domain admin if needed.

Currently, when we go to request the role its throws the below error

"An unexpected error occurred while trying to complete your request"

In the "Access-Manager-Webapp.log" it looks like the service account goes to assign the role but throws "Lithnet.AccessManager.Server.Authorization.RoleFulfillmentService|An error occurred when trying to grant JIT access to * for user ExampleDomain\Example Admin System.UnauthorizedAccessException: Access is denied.

I assume it's because the GMSA doesn't have permissions to assign users to Domain Admin? If so, is this not the use case this feature was designed for?

Cheers.

**Comment by ryannewington** [comment]
@TheImpossible21 

Certain groups like domain admins are protected by Active Directory and will have any ACL changes you make overwritten with the AdminSDHolder template

https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-c--protected-accounts-and-groups-in-active-directory

You'll need to modify this template, and add the GMSA with permission to modify the membership of the group to this ACL. Do note, that this template applies to all objects projected by the AdminSDHolder, as per the link above.
