### ISSUE TITLE
Access historical local admin passwords

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#228]
Hello,
since it's natively supported by Windows LAPS and we can get it through pws command, I think
it would be nice to have it into the Web interface, even without AMS agent, in the Community Edition.

Regards,
Red.

**Comment by ryannewington** [comment]
@red-erik Password history via web UI is available in enterprise edition of access manager as a paid feature.

**Comment by red-erik** [comment]
@ryannewington According to me, it does not make sense since it's a native windows feature, not requiring a "custom client" but, this is only my opinion. Anyway, thank you very much for your great work and for having a community edition as well.

Regards,
Red.

**Comment by ryannewington** [comment]
Thanks for the feedback @red-erik. It's always a delicate balance between enabling free features, and ensuring we have enough incoming revenue to continue developing and support the product. 

There are certain features we made available in community edition that were previously paid when windows laps came out (accessing encrypted laps passwords, for example). 

However password history, as a more advanced scenario remains an enterprise edition feature.
