### ISSUE TITLE
Save button on every main page

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#23]
Hello,
it would be nice to have a "SAVE" button on every main page of AMS. Sometimes I forgot to force a "save" from the File menu and, if the application crashed, I loose all my new configurations.

Regards,

Red.

**Comment by ryannewington** [comment]
I've got a ticket in #20 to make the crash scenario better. I can look at trying to auto-save here as well.

But it shouldn't be crashing in the first place. If there have been crashes, they'll be logged in the Windows 'Application' log with an entry from I think it's 'dot net runtime' or something like that. If you encounter any UI crashes, can you log an issue and include the contents of those event logs. There's usually two.

**Comment by red-erik** [comment]
I will
