### ISSUE TITLE
Logon Prompt for Intergrated Windows Authentication

### ISSUE THREAD

**Issue by w0tty55** [lithnet/access-manager#231]
If you use the integrated Windows Authentication you are automatically authenticated with the Windows logged in user by SSO. If you need the LAPS Password on another Client or will use JIT, you can't logon with my AMS User.
As an alternative you can use Basic Authentication. But that is insecure and there is no logoff button. 

**Describe the solution you'd like**
A authentication prompt for Windows integrated authentication.

**Comment by ryannewington** [comment]
@w0tty55 Unfortunately, when Windows Authentication is in play, the browser negotiates directly with the server, and our app does not have a chance to participate in this interaction. Using "Run as" to run the browser as another user is the only real solution here if you have to stick with IWA.
