### ISSUE TITLE
Unable to Edit User Interface on version 3.0.1210.0

### ISSUE THREAD

**Issue by dnauman1** [lithnet/access-manager#236]
I upgraded Access Manager to version 3.0.1210.0 from version 2.0.9519.0 on the Community Edition and am no longer able to edit the user interface. It says this is an enterprise feature. I did not see this being removed in the release notes. Is this a bug since v2 allowed editing the user interface on the community edition?

**Comment by jcspencer** [comment]
Hi @dnauman1,

That is correct, User Interface customization is now an [*enterprise edition*](https://docs.lithnet.io/ams/access-manager-editions) feature in AMSv3.

I have updated the [release notes for AMSv3](https://docs.lithnet.io/ams/whats-new#changed-features-1) to reflect this change; my apologies that it was not included in the initial release notes.

James

**Comment by dnauman1** [comment]
What is the reasoning to now make this an enterprise feature? Can you reconsider this change since I am sure I am not the only one who made customizations to the user interface? So, anyone using the community release has to roll back to v2 in order to be able to manage the user interface?

**Comment by ryannewington** [comment]
@dnauman1 

The decision was purely a commercial one. We're always seeking to find the right balance between our free core offering, and our paid versions. The ethos behind the free edition is that we want to help organizations better protect themselves from ransomware and help their adoption of LAPS. But supporting, writing and maintaining software isn't free. So we've tried to separate 'minimum security protections' from quality-of-life extras, and moved the latter into our paid product.

We didn't come at the decision lightly, and made special efforts to try and make sure this wasn't a surprise. When upgrading, the installer presents this screen which [links to this article](https://docs.lithnet.io/ams/installation/upgrading-from-v2/migration-consideration-from-v2) explaining the change.

![image](https://github.com/user-attachments/assets/d4351d8b-6b23-414f-9a18-fedc26fd0872)

But as you highlighted, we missed adding this to the release notes which people rely on, and as such you ended up getting the surprise we wanted to avoid.

V2 will continue to be supported for the next couple of years (we'll be releasing a minor update before the end of the year to update to .NET 8), so staying on V2 is the way to go if UI customization is important to you.

My apologies again for catching you off guard with this one. We'll look to see if we have any other gaps in our coverage to help preventing this from happening to others.
