### ISSUE TITLE
RapidLAPS - Unable to complete the RapisLAPS login process due to licensing issues

### ISSUE THREAD

**Issue by astular** [lithnet/access-manager#237]
I have configured RapidLAPS for logins and elevation. The client correctly receives the policy and the "Elevate with RapidLAPS" option is now shown when I try to run an application as administrator. When I provide a reason (User prompt, configured in the default policy) and click Submit, I receive "Unable to complete the RapidLAPS process" message on the client.
If I check the server logs, this is what I get in the access-manager-api.log:
2024-08-19 14:19:40.0405|ERROR|864|00-70ee0ba5af13c331d6e57248711d4f91-2891bf9d8e692199-00|10.4.1.88|LithnetAccessManagerAgent/3.0.1210.0|Lithnet.AccessManager.Api.ApiExceptionHandler|A licensing error occurred
Lithnet.Licensing.Core.NoLicensePresentException: There is no valid license on the system

I have attached the complete log.

I am using the community edition, version 3.0.1217.0.

![20240819_142545](https://github.com/user-attachments/assets/ee922fac-d45a-4e88-84bd-cb32cf043049)
![20240819_142539](https://github.com/user-attachments/assets/cba05a5b-e120-444c-93ff-8e2be36f9fe3)
![20240819_142516](https://github.com/user-attachments/assets/861163c5-761a-4c6e-864f-682bcda49e0b)

Have I done something wrong? What could be the reason?

**Comment by ryannewington** [comment]
@astular Thanks for the detailed report and log files. Can you try this build?

https://packages.lithnet.io/win/access-manager-service/v3.0/x64/LithnetAccessManagerService-3.0.1218.0-x64.exe

**Comment by astular** [comment]
Hi! I have installed version 3.0.1218.0 and rebooted the server. The situation has changed, RapidLAPS is now working for logon, but not for elevation. The process of elevation correctly displays the QR code. When I scan the code, the phone correctly opens the Access Manager page and open the form where I provide an approval reason. When I click on "Approve" button, the page displays the error message "An unexpected error occured".
I have tried to change the Authorization rule for my account to "Do not prompt for a reason". But still, when I click on "Approve" the same error is displayed.
As said, this is not the case with RapidLAPS logon, where the logon process completes correctly upon approval.

This is the error that I receive in the logs:
![image](https://github.com/user-attachments/assets/14c5923c-006c-462b-a03c-0672d1704815)
The error is also logged in the access-manager-webapp.log file:
![image](https://github.com/user-attachments/assets/f9a36dea-9eb1-45c8-ab02-4366ee90d3c9)

**Comment by ryannewington** [comment]
@astular this is a strange one. Can I ask what process you were trying to elevate? Was it built in windows EXE or something else?

**Comment by astular** [comment]
Yesterday I was trying to elevate Command Prompt in Windows 11, today I tried with Microsoft Office Download Tool and the result is the same.
This is what the confirmation page looks like on my phone:
![image](https://github.com/user-attachments/assets/0c96e249-3dfd-44ef-9ead-89150d6e1f7c)
I will test today with another computer, for example a Windows 10 client.

**Comment by ryannewington** [comment]
Hmm ok. that 'process' should be cmd.exe not consent, so i think something is going wrong with getting that data from windows, which is causing the Audit error seen down the line.

What version of Windows 11 are you running? can you check with `ver` on the command prompt, ans assuming this is x64 not arm64 windows 11?

**Comment by astular** [comment]
Hi! I am using Windows 11 x64, version is:
Microsoft Windows [Version 10.0.26100.1586]

Internet says that consent.exe is part of the UAC mechanism. I am already installing an agent on a Windows 10 machine, to test there.

**Comment by ryannewington** [comment]
and if you type `echo %systemroot%` is its value `C:\Windows`?

**Comment by astular** [comment]
Yes, C:\WINDOWS
![image](https://github.com/user-attachments/assets/1093b1d0-d322-4609-8c3f-fa3dc0918756)

**Comment by ryannewington** [comment]
Oh that's a windows insiders preview build?

**Comment by astular** [comment]
Oh, yes, that I correct, sorry. I will test on a GA build and also on a Windows 10 computer.

**Comment by ryannewington** [comment]
Ok here's a fix in for the bug that's preventing you from approving the elevation - The cause of that bug is the data *about* the elevation is missing. Microsoft must have changed something in that insider build. We'll get that insider deployed in our lab and have a look. In the mean time, this patch means you'll only see 'consent' as the process being elevated, but you should be able to elevate. 

https://packages-dev.lithnet.io/win/access-manager-service/v3.0/x64/LithnetAccessManagerService-3.0.1219.0-x64.exe

**Comment by astular** [comment]
I can confirm your statement. On a Windows 10 machine RapidLAPS works and offers much more details about the process:
![image](https://github.com/user-attachments/assets/1dfe30fe-0835-4930-a1bd-33907ac18077)

Thank you very much for the quick fix. I will test it. And I will also test RapidLAPS on a Windows 11 GA version.

**Comment by astular** [comment]
I can confirm that your fix 3.0.1219 works on Windows 11 Preview. 
I can also confirm your statement regarding the consent.exe, Microsoft must have changed that in the preview build. Because the GA version of Windows 11 still works in the same way as windows 10.
Thank you very much for promptly fixing my problem! You can close the ticket.

**Comment by ryannewington** [comment]
@astular could I trouble you for the credential-provider.log file from C:\Program Files\Lithnet\Access Manager Agent\logs?

**Comment by ryannewington** [comment]
from the insiders preview machine where it failed

**Comment by ryannewington** [comment]
Not to worry, we were able to reproduce this and get the logs needed

**Comment by ryannewington** [comment]
We've got a fix for 24H2 support in v3.0.1227 available here: [https://packages.lithnet.io/win/access-manager-service/v3.0/x64/latest](https://packages.lithnet.io/win/access-manager-service/v3.0/x64/latest.lnk)

Please let me know if this resolves the issue for you.
