### ISSUE TITLE
Adding Automatic JIT group creation rules in bulk

### ISSUE THREAD

**Issue by RygenX01** [lithnet/access-manager#238]
Hi Ryan,

I am adding multiple (Hundreds) "Automatic JIT group creation" rules in Lithnet AMS by hand at the moment. Is there a way to automate this? I could not find any Powershell commands regarding this in the documentations. If this is not possible i would like to request this as a feature in the future.

Regards,
Rik Winteraeken

**Comment by ryannewington** [comment]
Hi Rik,

Do you want to reach out to us via the support contact (Damien should have this)?

Ryan

**Comment by RygenX01** [comment]
Hi Ryan,

I will do that!

Thanks!
Rik
