### ISSUE TITLE
[HELP] What is the proper way to specify the AMS server port in the agent config?

### ISSUE THREAD

**Issue by jperhamcatchteam** [lithnet/access-manager#242]
We've been running Lithnet AMS for years now.  This morning, I went to install the agent on a new Ubuntu VM and cannot get it to start with my previously documented and working command line instruction:

`$ /opt/LithnetAccessManagerAgent/Lithnet.AccessManager.Agent --server ams.direct.<redacted>.net:4443 --registration-key <key redacted>
`
It appears to no longer accept the port for the server but without it, it also doesn't connect.  What am I missing here?

Here's the log:

`Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]: Lithnet.AccessManager.Agent.WorkerService[1000] Lithnet Access Manager Agent has started. v3.0.1210.0 (64-bit)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]: Lithnet.AccessManager.Agent.WorkerService[1007] An unexpected error occurred System.UriFormatException: Invalid URI: The hostname could not be parsed.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)    at System.Uri..ctor(String uriString)    at System.UriBuilder.get_Uri()    at Lithnet.AccessManager.Agent.HostBuilderExtensions.BuildBaseUriAsync(IServiceProvider serviceProvider) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 142    at Lithnet.AccessManager.Agent.HostBuilderExtensions.<>c.<ConfigureAccessManagerAgent>b__3_3(IServiceProvider serviceProvider, HttpClient c) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 67    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)    at Lithnet.AccessManager.Agent.Providers.AmsApiHttpClient.IsApiReachable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Providers/AmsApiHttpClient.cs:line 50    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CheckApiAvailable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 59    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CanProceedAsync(PrerequisiteCheckPhase phase) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 29    at Lithnet.AccessManager.Agent.WorkerService.ExecuteAsync(CancellationToken stoppingToken) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/WorkerService.cs:line 37
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]: Microsoft.Extensions.Hosting.Internal.Host[11] Hosting failed to start System.UriFormatException: Invalid URI: The hostname could not be parsed.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)    at System.Uri..ctor(String uriString)    at System.UriBuilder.get_Uri()    at Lithnet.AccessManager.Agent.HostBuilderExtensions.BuildBaseUriAsync(IServiceProvider serviceProvider) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 142    at Lithnet.AccessManager.Agent.HostBuilderExtensions.<>c.<ConfigureAccessManagerAgent>b__3_3(IServiceProvider serviceProvider, HttpClient c) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 67    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)    at Lithnet.AccessManager.Agent.Providers.AmsApiHttpClient.IsApiReachable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Providers/AmsApiHttpClient.cs:line 50    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CheckApiAvailable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 59    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CanProceedAsync(PrerequisiteCheckPhase phase) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 29    at Lithnet.AccessManager.Agent.WorkerService.ExecuteAsync(CancellationToken stoppingToken) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/WorkerService.cs:line 37    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]: Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at System.Uri..ctor(String uriString)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at System.UriBuilder.get_Uri()
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.HostBuilderExtensions.BuildBaseUriAsync(IServiceProvider serviceProvider) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 142
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.HostBuilderExtensions.<>c.<ConfigureAccessManagerAgent>b__3_3(IServiceProvider serviceProvider, HttpClient c) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Extensions/HostBuilderExtensions.cs:line 67
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.Providers.AmsApiHttpClient.IsApiReachable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/Providers/AmsApiHttpClient.cs:line 50
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CheckApiAvailable() in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 59
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.NetworkReadyPrerequisite.CanProceedAsync(PrerequisiteCheckPhase phase) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/PrerequisiteChecks/NetworkReadyPrerequisite.cs:line 29
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.WorkerService.ExecuteAsync(CancellationToken stoppingToken) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Shared/WorkerService.cs:line 37
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Sep 11 14:57:51 projectvm01 LithnetAccessManagerAgent[91177]:    at Lithnet.AccessManager.Agent.Linux.Program.Main(String[] args) in /home/vsts/work/1/s/src/Lithnet.AccessManager/Lithnet.AccessManager.Agent.Linux/Program.cs:line 28
Sep 11 14:57:51 projectvm01 systemd[1]: LithnetAccessManagerAgent.service: Main process exited, code=dumped, status=6/ABRT`

**Comment by ryannewington** [comment]
@jperhamcatchteam 

Just took at a look at the code, and it was a bit of a fluke that it worked in the last version, and not this version.

If you manually edit the `/etc/LithnetAccessManagerAgent.conf` file, under the `"Server":"abc",` element, you can add a `"Port":4443,` element as a workaround.

We'll get a command line argument added that allows you to specify the port in a future version.

Do note that the v3 agent version you are installing requires your server to be upgraded to v3 as well. If your server is still on v2, then you'll need to use the v2 agent.

**Comment by jperhamcatchteam** [comment]
Thank you for the reply.  That worked for my Linux hosts.

For anyone that comes across this with the same issue:

For Windows, the config location is in the registry at **HKEY_LOCAL_MACHINE\SOFTWARE\Lithnet\Access Manager Agent**

You need to add a new **String Value** with the name of **Port** and the **Data** containing the port number.
