### ISSUE TITLE
ADMX templates missing

### ISSUE THREAD

**Issue by PrieserMax** [lithnet/access-manager#245]
Hello,
I would like to install the agent via GPO for Rapidlaps and configure the client settings via GPO.
Sadly the templates are missing and are non-existent in the directory in this (https://docs.lithnet.io/ams/help-and-support/advanced-help-topics/group-policy-configuration) article.
Is there a way to manually download them?
Greetings
Max

**Comment by PrieserMax** [comment]
Update:
Just rolled it out via my software deployment via the CMD registration, works perfectly

**Comment by ryannewington** [comment]
@PrieserMax 

Glad you got it working via cmd line.

Regarding the original problem, are you saying the ADMX files were not in `C:\Windows\PolicyDefinitions`, after installing the agent?

I've checked a fresh install and I can see them there, so not sure what's going on if thats the case. What version are you installing and what OS build are you running?

**Comment by PrieserMax** [comment]
Good morning @ryannewington 
I just misread the documentation, error on my side. ->I looked on the server for the ADMX templates and completely overlooked, that they were installed on the Agent computer...
Thank you for your help!
Greetings
Max

**Comment by ryannewington** [comment]
Ah no problems at all. Thanks for confirming Max
