### ISSUE TITLE
[HELP] Access from Android with NTLM

### ISSUE THREAD

**Issue by PrieserMax** [lithnet/access-manager#247]
### Subject of the issue
Hello,
I'm trying to access the web-ui from Android.
In none of my browsers appears a pop-up asking for the credentials (Firefox, Edge, Chrome)
How could I change it, that I cann access it from Android?
Greetings
Max

**Comment by ryannewington** [comment]
What version of the server are you running?

**Comment by PrieserMax** [comment]
> What version of the server are you running?

I'm running the latest (according to the Config utility) 3.0.1229.0 community edition

**Comment by ryannewington** [comment]
What auth mode are you using? Negotiate + NTLM?

**Comment by PrieserMax** [comment]
> What auth mode are you using? Negotiate + NTLM?

Thank you very much. That was the problem -> Was set to NTLM, but nut Negotiate + NTLM so of course it didn't work on Android.
