### ISSUE TITLE
Default AMS firewall rule incorrectly sets the process

### ISSUE THREAD

**Issue by s881628** [lithnet/access-manager#27]
**Issue Description**

The default firewall rule that is created when saving the AMS configuration for the first time is incorrectly setting the process to  "C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Service.exe".
This rule does not permit traffic to the Access Manager Portal.  
Setting the process in the rule to "System" resolves the issue.  We are using HTTP.SYS to host the page and that runs as system not the AMS service account, so the rule should be referencing System as the process.

![image](https://user-images.githubusercontent.com/20349934/92820957-e7dd1780-f40d-11ea-9159-3f66d6efadc3.png)

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.
