### ISSUE TITLE
Smart Card Certificates logon

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#28]
Hello,
the new version with AltSecurityIdentities seems not to be working.
With NtAuthStore I receive :
Lithnet.AccessManager.CertificateValidationException: The certificate could not be validated against the NTAuth store. Ensure the issuer is from a trusted enterprise smart-card issuing CA
With Trust any certificate... I receive:
Lithnet.AccessManager.DirectoryException: DsBind failed
---> System.ComponentModel.Win32Exception (1355): The specified domain either does not exist or could not be contacted.

What kind of check AMS is trying to do ?
AuthStore contains ONLY the Issuing CA (as required by Smart Card Logon). Root Ca and Issuing CA are not in my Active Directory but are external and NOT integrated in any AD.

Regards,

Red.

**Comment by ryannewington** [comment]
Hey Red. Can you email me the AMS log from a logon attempt?

Validating the certificate against nt auth is just a standard windows api call. We use the same api that smart card logon uses, so the rules will be the same. Only the issuer needs to be in the NT auth store. Not the root.

**Comment by red-erik** [comment]
Log sent as requested.

Red.

**Comment by ryannewington** [comment]
Thanks Red,

Is it possible to send me the certificates (without the private key of course) of the user, issuing CA, and Root CA? I'll add these to my local NTAuth store and see what is going on.

We use NTAuth store validation in my environment, and it works fine, but we use an AD CA. So there must be something different about the external CA that I am missing. I can't see anything obvious in the logs, so I'll need to try to reproduce it.

If you can't share the certificate chain, I'll have to try and add additional logging to the certificate function and maybe get you to run some diagnostic tools. I'll need a couple of days to prepare for this.

The 'DsBind' error that you get when NTAuth is turned off, is because it's trying to resolve the UPN in the certificate of

`<name>@external.<domain>.com`

But the local DC locator cannot find a domain `external.<domain>.com` which is expected, as I understand your setup. This is your RFC822 address, not the AD UPN.

You'll need to disable UPN lookup and enable only altSecurityIdentities as per this article https://github.com/lithnet/access-manager/wiki/Enabling-AltSecurityIdentities if you have UPNs that aren't resolvable in the certificate. AltSecurityIdentity support is not on by default.

**Comment by red-erik** [comment]
Hello,
 a little bit difficult for me to send the certificates, anyway, even forcing "trust only this specific issuer" I receive
Lithnet.AccessManager.CertificateIdentityNotFoundException: The request could not be processed because the authenticated user was not found in the directory. Claim information:
..
at Lithnet.AccessManager.Service.AppSettings.CertificateAuthenticationProvider.ResolveIdentity(CertificateValidatedContext context) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\CertificateAuthenticationProvider.cs:line 192
at Lithnet.AccessManager.Service.AppSettings.CertificateAuthenticationProvider.<Configure>b__10_1(CertificateValidatedContext context) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\CertificateAuthenticationProvider.cs:line 91

According to my understanding, there is something wrong in how AMS search for the user: my AltSecurityIdentities contain my RFC822 property of my certificate and Smart Card logon is working as expected in my AD.
My json is:
"ClientCert": {
      "RequiredEkus": [],
      "ValidationMethod": "NtAuthStore",
      "RequireSmartCardLogonEku": false,
      "TrustedIssuers": [],
      "IdentityResolutionMode": "AltSecurityIdentities"


Regards,

Red.

**Comment by ryannewington** [comment]
Ok we have two issues in this case

1. NTAuth store validation is failing for a externally issued certificate
2. The IdentityResolutionMode value in the config file seems to be getting ignored. If you have it set to AltSecurityIdentities as per your comment, it should not even be trying to do UPN lookup. 

Note, that without NTAuth store validation, you can't use rfc822 altSecurityIdentity, so we'll need to fix that first. 

Can you send me your config file so I can investigate issue #2, and I'll come back with a plan for diagnosing the NTAuth issue.

**Comment by red-erik** [comment]
Done.

**Comment by ryannewington** [comment]
Thanks. 

And on the AMS server itself, can you confirm the issuing CA of the smart card certificate appears when running this command?

certutil -enterprise -viewstore NtAUTH

**Comment by red-erik** [comment]
Hello,
I receive "No certificate available" but we don't have an Autoenrollment policy for server. Anyway, we have a GPO to distribute certificate to all systems and all certificates are present in the local server stores (Root and Intermediates).

**Comment by red-erik** [comment]
Same result:
The request could not be processed because the authenticated user was not found in the directory
with correct json, ntauth setting and certutil -enterprise -viewstore NtAUTH showing correct certificates

**Comment by ryannewington** [comment]
I've done some research on this, and it seems that the local NTAuth store cache is only populated when an autoenrolment policy is enabled. Even if no certificates are set to auto enrol. http://www.cievo.sk/2012/07/02/problem-with-enterprise-certificate-distribution/

A very strange behavior. You can use the certutil command to add it to the cache if you don't want to enable the policy.

`certutil -enterprise -addstore NTAuth CA.cer`

I'll have a debug build shortly to gather more information on why the AltSecurityIdentity resolution method is being bypassed.

**Comment by ryannewington** [comment]
Hi Red,

Can you clear your log, install this build, try to authenticate with smart card again, and send the resulting log file.

https://github.com/lithnet/access-manager/releases/tag/v1.0.7615.0-beta.2.1

**Comment by red-erik** [comment]
Hello,
I'm aware of local NTAuth not populated automatically but I did it manually. I'm sending you the new logs but with the same results.

**Comment by red-erik** [comment]
Hello,
any news on this topic ?
Regards,

Red.

**Comment by ryannewington** [comment]
Hi red,

I replied to your last email on Thursday. Did you not get it?

**Comment by red-erik** [comment]
Hi,
missed and replied now. I'll test again with RFC822

Regards,

Red.

**Comment by red-erik** [comment]
My mistake, I confirm it is working fine with RFC822.
Thank you very much.

Regards,

Red.

**Comment by red-erik** [comment]
As a last evolution, it would be fine to support all available values for AltSecurityIdentities as specified by
![Auth](https://user-images.githubusercontent.com/10245160/93749446-39e62000-fbfa-11ea-86e4-8d82018a9663.JPG)
anyway, thank you very much for your great work.
Regards,
Red.

**Comment by ryannewington** [comment]
They are all supported, but I built the `<S>` element in the wrong order. Which is why it didn't match for you. I'll get that fixed in beta 3

**Comment by red-erik** [comment]
Waiting to test it :-)

Red.

**Comment by ryannewington** [comment]
This feature is now in beta-3

https://github.com/lithnet/access-manager/releases/tag/v1.0.7624.0-beta.3
