### ISSUE TITLE
HA Access Manager

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#30]
I'm wondering how one would set up HA? Do you support synchronization of sorts between two or more instances? I guess having a critical part of infrastructure based on Access Manager on just one node is asking for trouble.  It would be cool to have 2-4 nodes for larger infrastructures.

**Comment by ryannewington** [comment]
Failover cluster would be supported, but I haven't tested it yet.

Other options are two or more nodes behind a load balancer with IP stickiness, and something to copy the config folder between them.

**Comment by ryannewington** [comment]
You can redirect the config file to a new location be creating a reg key

`HKEY_LOCAL_MACHINE\SOFTWARE\Lithnet\Access Manager Service\ConfigPath`

This would allow you to store the config files on the cluster shared volume.

**Comment by ryannewington** [comment]
One issue with clustered instances would be that SMTP passwords could only be decrypted on the machine where they were saved from the UI. As a workaround, you can edit the appsettings.json file, and put the password in plain text by turning off encrpytion for the value
So you'd change this

```
 "Email": {
    "Port": 25,
    "UseSsl": false,
    "UseDefaultCredentials": false,
    "Username": "test",
    "Password": {
      "Data": "<encrypted blob>",
      "Salt": "<salt>",
      "Mode": 1
    }
  },
```
To this

```json
 "Email": {
    "Port": 25,
    "UseSsl": false,
    "UseDefaultCredentials": false,
    "Username": "test",
    "Password": {
      "Data": "mypassword",
      "Salt": null, 
      "Mode": 0
    }
  },
```
