### ISSUE TITLE
Cannot update AMS GMSA service account after initial setting

### ISSUE THREAD

**Issue by jaysnrye** [lithnet/access-manager#32]
**Describe the bug**
Trying to update the AMS service account to use a GMSA after the initial installation causes an unexpected object type exception.
Nothing is logged other than the error presented in the application dialog 

**To Reproduce**
1. Within AMS Web Hosting Page select " Change Account"
2. Enter the new GMSA
3. Select OK

**Expected behavior**
The service account should accept a GMSA as its new service account

**Screenshots**
![image](https://user-images.githubusercontent.com/20349934/93966177-5e332f80-fda7-11ea-8ab5-3cddb8fffe2e.png)

**Comment by red-erik** [comment]
Hello,
sorry for the question but did you entered the final "$" character at the end of the GMSA account ?
I'm asking this 'cause I did this mistake some time agò configuring Windows services.

Regards,

Red.

**Comment by ryannewington** [comment]
Good thinking @red-erik, but this one was a bug in the code

**Comment by s881628** [comment]
> Hello,
> sorry for the question but did you entered the final "$" character at the end of the GMSA account ?
> I'm asking this 'cause I did this mistake some time agò configuring Windows services.
> 
> Regards,
> 
> Red.

Hi Erik,

That is a good tip and definitely required for a gmsa, however it was entered this time around. 
Thanks for the feedback

**Comment by ryannewington** [comment]
Will be fixed in beta3, and to @red-erik's point, I added some helper text to the page

![image](https://user-images.githubusercontent.com/17229877/94074297-583b5e00-fe3c-11ea-8169-cd35824e7047.png)

**Comment by ryannewington** [comment]
This issue is fixed in beta-3

https://github.com/lithnet/access-manager/releases/tag/v1.0.7624.0-beta.3
