### ISSUE TITLE
Problem in reading the local security group membership of an account from another domain

### ISSUE THREAD

**Issue by Alex4e4** [lithnet/access-manager#33]
I attached the architecture to make it clearer
Access Control install in subdomain B.
LAPS Clients in all domains.
I will describe the situation.
I create a local security group in subdomain B and add an account from subdomain A to it. Then I assign the rights to the created group to OU 1 in subdomain B. Everything works fine, account can see password. 
When I create a local security group in subdomain A, I add an account from domain A to it and delegate authority to the group to OU 1 in subdomain A. Doesn't work. Laps writes that the account does not have permission to view the password of this computer.
In the second case, it only starts working when I change the scope from local to universa
If you add rights for OU1 from subdomain A, it does not allow you to select a local security group from domain B.
I think it is worth either adding to the instruction that only universal groups should be used, or fixing this trouble
l
![AD_Arch](https://user-images.githubusercontent.com/72306285/94992666-42444080-0594-11eb-9ce2-008b04e7ff2b.jpg)

**Comment by ryannewington** [comment]
Hey @Alex4e4 

This behaviour is expected, as access manager asks the domain where the computer is located t build the access token. So you need to be aware of this when assigning access to domain local groups.

More information is here

https://github.com/lithnet/access-manager/wiki/Access-evaluation-in-Access-Manager-Service-(AMS)
