### ISSUE TITLE
"Submitting request..." shows incorrectly when a form error is present

### ISSUE THREAD

**Issue by Alex4e4** [lithnet/access-manager#34]
When you enter the window for requesting a password for a computer, you leave the comment field empty, it gives an error about the need to enter a comment. But when this window continues to spin endlessly and does not allow you to enter a comment, the problem is solved ONLY by reloading the page. More details in the screenshot. For security reasons, I hid the computer name in the screenshot.
Inscription "Submitting request..." with loading icon not cleared until you reload the page in the browser. I am using browser Google Chrome.
It would be great if the inscription "Submitting request..." disappears afterwards and does not have to reload the page completely
![request_access4](https://user-images.githubusercontent.com/72306285/94992786-f6de6200-0594-11eb-9554-80c8948a10eb.jpg)
![request_access3](https://user-images.githubusercontent.com/72306285/94992788-f776f880-0594-11eb-9930-650f9ac0f510.jpg)
![request_access2](https://user-images.githubusercontent.com/72306285/94992789-f80f8f00-0594-11eb-9492-7d7d7a485964.jpg)
![request_access1](https://user-images.githubusercontent.com/72306285/94992790-f80f8f00-0594-11eb-8894-beb20555163a.jpg)

**Comment by ryannewington** [comment]
Thanks for the report. 
This is fixed in beta 3

**Comment by ryannewington** [comment]
This issue is fixed in beta-3

https://github.com/lithnet/access-manager/releases/tag/v1.0.7624.0-beta.3
