### ISSUE TITLE
Authorization rules list shows incorrect column header text

### ISSUE THREAD

**Issue by Alex4e4** [lithnet/access-manager#35]
![bag](https://user-images.githubusercontent.com/72306285/94993051-ee872680-0596-11eb-8592-d48019e24f02.jpg)

**Comment by ryannewington** [comment]
Fixed in beta 3

**Comment by ryannewington** [comment]
This issue is fixed in beta-3

https://github.com/lithnet/access-manager/releases/tag/v1.0.7624.0-beta.3
