### ISSUE TITLE
Application/Group JIT

### ISSUE THREAD

**Issue by dafunky1** [lithnet/access-manager#40]
We already have an extensive JIT-groups structure built out for applications/groups that utilizes TTL group memberships. It would be amazing if we could consolidate that functionality into this tool. 

I realize your intention is not to build out a complete PAM solution (according to your response on the approval system feature), but it seems like this request lines up with your intention and the technology. 

Possible implementation:
1. Another field on the Request Access page to include 'Group name'
Would require quite a bit more logic and code rewrite, but would be the cleanest and most logical
2. Change 'Computer name' to something more ambiguous like 'Name'
We could easily use the current system and simply create computer accounts associated with those already created JIT groups, but it would be less confusing for the users of the system if they don't see 'Computer Name' when requesting access for an application or group

**Comment by ryannewington** [comment]
Hi @dafunky1 

This is definitely on the roadmap. The feature will include support for roles, which can either be TTL groups, or via PowerShell extension so you can JIT and unJIT 3rd party things that don't use AD groups. However, I'm planning for this to be in an 'enterprise' edition of the product. The goal will be to provide everything needed for an organization to defend itself against lateral-movement based attacks in the free standard edition, and capability outside that scope will fall into the enterprise add on. There's a fair bit of work still to do in order to make this happen, but I've got a big need for it myself in my org, so will be one of the first to start work on once the core product is signed off.

**Comment by dafunky1** [comment]
That is great news! This product is really addressing a need that PAM systems just do not do well. Looking forward to the public release!

**Comment by PrzemyslawKlys** [comment]
I was about to ask if you would accept PR's for the approval process - but now that you announced enterprise/pay edition I guess this is where we're going to get it right?

**Comment by ryannewington** [comment]
Most likely. Approvals requires some kind of persistent storage, which I had been keen to avoid to keep the app light and simple, and reduce its surface area as much as possible. People will be running this thing in tier 0, and I need to be conscious of that from a design perspective. Throwing an SQL server on top of this is a big ask. However, to do non-TTL group based JIT will require persistent storage of some sort, so it seems there is no getting away from having it. However, the tier zero concerns are still present, and keeping this simple and as small as possible is important. High availability is also another concern and adds another layer of complexity. So.... essentially, some of the additional features have requirements that open the door to supporting approvals, but there is a lot of internal architecture to do before we can drop that support in.

The details on enterprise edition aren't by any means finalized. This isn't about making a crippled product that is useless unless you pay $. I want every org to be able to protect itself from lateral-movement based attacks. That core capability is the product. But open source isn't free to make, and support. With 30+ projects and hosting costs, domains, web sites, certificates, I'm out of pocket a fair bit. Donations are few and far between, and is often not something organizations can do. So this is a way for orgs to make contributions, get access to additional features outside of the core product goals, and invest in the core product for everyone else. Hopefully it is a model that makes sense. I'm striving to find the right balance.
