### ISSUE TITLE
Schema deployment status doesn't refresh

### ISSUE THREAD

**Issue by s881628** [lithnet/access-manager#6]
**Steps to Reproduce**

1. Open Access Manager Configuration GUI and click Active Directory on the left side menu
2. Note Lithney Access Manager Schema is listed as "Not Present"
3. Deploy Schema
4. Return to the GUI and click "Refresh Status"
5. Note the Schema status is not updated

**Expected Result**
After clicking "Refresh Status" I expect the Schema deployment status to change to  "present"

**Actual Result**
Despite clicking "Refresh Status" the status of the Schema deployment is still listed as "Not Present"

**Workaround**
Close the GUI and reopen.  Note the service does not need to be restarted, only the GUI relaunch.

**Comment by ryannewington** [comment]
I think the schema was cached locally. I have added an instruction to reload the schema cache each time it is checked. Are you able to validate it works as expected?

**Comment by ryannewington** [comment]
Rolled back the previous fix because it was refreshing the server schema, not the client schema

**Comment by ryannewington** [comment]
Fixed in 1.0.7593.0
