### ISSUE TITLE
Negotiate authentication is incorrectly allowed over HTTP

### ISSUE THREAD

**Issue by janssen-bart** [lithnet/access-manager#65]
**Describe the bug**
We noted that https is not enforced. When you load the page via "http" and you give your credentials, they are sent in plain text over the network. HTTPS should load directly, it should not be possible to load the page via http. Now he redirects to the "https" page  after your first attempt via "http". The first time the data is sent in plain text over the network. Because of the impact this
application can have, we see this as a high issue.

**To Reproduce**
This Password is asked when we try to reach the application in different domain. 

**Expected behavior**
The website is available over HTTP and does not enforce the user to use HTTPS. When a user visits a websites over a non secure
connection all data is sent in plain text and can be intercepted by an attacker via a man-in-the-middle attack.

**Screenshots**
![image](https://user-images.githubusercontent.com/36771708/103218156-9738ee00-491a-11eb-9b04-06c8052f9362.png)

**Access Manager installation**
 - OS: Windows Server 2019
 - Version 1.0.7846.0

**Comment by ryannewington** [comment]
Thanks for reporting these issues @janssen-bart, and for the detailed repors. I'll look into these in a couple of weeks when I'm back from break and include the fixes in the next release.

**Comment by ryannewington** [comment]
Thanks for the detailed report again @janssen-bart.

This seems to be a fundamental issue in asp.net core. I've removed HTTP support from the core host engine, and added a secondary host engine listening on the HTTP port that is configured only for anonymous authentication, and simply performs redirection to HTTPS. This will stop IWA authentication from taking place over HTTP, before the HTTPS redirection middleware can kick in.

**Comment by ryannewington** [comment]
Fixed in release candidate 1 https://github.com/lithnet/access-manager/releases/tag/v1.0.7872-rc1
