### ISSUE TITLE
 HSTS max-age too short

### ISSUE THREAD

**Issue by janssen-bart** [lithnet/access-manager#66]
**Describe the bug**
The time used in the HTTP Strict Transport Security header is too short.

HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Set-Cookie: .AspNetCore.Antiforgery.oocKVwBnr8s=CfDJ8Cxfmzn0qmlLrwRcO2Ipv2xx8ejhlAXOdjr7Jo3yp70TPuN0cxWfczxrOwmRKU7Ikefdq79ZaBFMQQBzSY5CjE6725azdn2qljgoDCvBeMBAfm17569SDD6PX8C11c1AfGQcLAhMUm5MUI0fxz8Ac; path=/;
samesite=strict; httponly
Server: Microsoft-HTTPAPI/2.0
**Strict-Transport-Security: max-age=2592000**
Feature-Policy: geolocation 'none';midi 'none';notifications 'none';push 'none';sync-xhr 'none';microphone 'none';camera
'none';magnetometer 'none';gyroscope 'none';speaker 'self';vibrate 'none';fullscreen 'self';payment 'none';

**Expected behavior**
In order to remediate this issue, implement a HSTS header with a sufficiently long max-age.
The max-age of 1 year is recommended, making the header look like this:
**Strict-Transport-Security: max-age=31536000**

The max-age in a HTTP Strict-Transport-Security header indicates how long a browser remembers a HSTS header was present
on the application.
Having a max-age which is too low (< 1 year) allows an attacker to simply wait until a user hasn't visited the website for a while (and
the browser has forgotten about the presence of HSTS) to then strip the header in a new Man in the Middle attack.

**Comment by ryannewington** [comment]
Have increased this to 1 year. Should this be a configurable option? Or is one year sufficient for all use cases.

**Comment by janssen-bart** [comment]
Hi,
Thanks for all the effort already :-). I don't see any benefit to parameterize this setting in the GUI. The HSTS Best Practices is to assign the max-age directive’s value to be greater than 10368000 seconds (120 days) and ideally to 31536000 (one year).

According to the highest standard it is OK to set 1 year.

**Comment by ryannewington** [comment]
Thanks for confirming. Will leave it set to one year

**Comment by ryannewington** [comment]
Fixed in release candidate 1 https://github.com/lithnet/access-manager/releases/tag/v1.0.7872-rc1
