### ISSUE TITLE
Secure/httponly flags missing on cookies

### ISSUE THREAD

**Issue by janssen-bart** [lithnet/access-manager#68]
**Background**
During testing we discovered that the secure and httponly flags were missing from multiple cookies in both applications.
The secure flag makes sure a cookie can not be sent over unencrypted channels, protecting the cookie from being stolen through a large variety of Man in the Middle attacks.
The httponly flag makes sure the cookie can not read from javascript, protecting the cookie from being stolen through use of a large variety of javascript-based attacks (such as cross-site scripting).

**Remediation**
In order to remediate this issue, make sure the secure flag is set on all cookies and the httponly flag is set on all cookies which are not read through javascript during normal use of the application.

**Comment by ryannewington** [comment]
Cookie policy has been adjusted to enforce HttpOnly = true, Secure = True.

**Comment by ryannewington** [comment]
Fixed in release candidate 1 https://github.com/lithnet/access-manager/releases/tag/v1.0.7872-rc1
