### ISSUE TITLE
Access Manager Website doesn't load after initial install

### ISSUE THREAD

**Issue by s881628** [lithnet/access-manager#7]
**Steps to Reproduce**

1. Perform a vanilla install of AMS
2. Select a certificate (I generated a self signed using `New-SelfSignedCertificate -DnsName client1.tnb.local -CertStoreLocation "cert:\LocalMachine\My"` )
3. Save Configuration.
4. Open browser on the server or a client and browse to https://localhost or https://FQDN
5. Note page doesn't load

**Expected Result**
The website should have loaded

**Actual Result**
Server returns an error "INET_E_RESOURCE_NOT_FOUND"

**Comment by ryannewington** [comment]
So we need to restart the service after setting the initial config. Maybe we should just do this automatically?

**Comment by s881628** [comment]
So I found the cause for this intermittent issue.
There is a delay in the network stack coming up on occasion in my lab after a reboot.  The service is attempting to start before it can connect to the DC to authenticate the GMSA.

Possible improvement here is to have the installer set the service to Automatic (Delayed Start) and set the failure action to retry.

**Comment by ryannewington** [comment]
I think as this is an issue specific to lab environments and unlikely to be seen in a production environment, I'll leave it as automatic in the installer.
