### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by janssen-bart** [lithnet/access-manager#73]
On https://github.com/lithnet/access-manager/wiki/Setting-up-authentication-with-Azure-AD part 1 step 5 contains a trailing /

According to 
![trailing](https://user-images.githubusercontent.com/36771708/106291084-78948280-624b-11eb-9b6b-85bfda9e49a0.png)

This should not. After testing we can confirm.

**Comment by ryannewington** [comment]
Thanks for the feedback. I've updated the wiki page
