### ISSUE TITLE
problem with delegating rights to a group of computers in another domain of the same forest Active Directory

### ISSUE THREAD

**Issue by Alex4e4** [lithnet/access-manager#78]
We have Active Directory Forest. A WebLaps server has been installed in one forest domain and a service account (gMSA) has been created with the rights to read and reset LAPS passwords.
We need to organize access to a group of computers of another domain. All the computers in the domain are assembled with a global security group.
When you try to get a password from Laps, we get the error "You are not authorized to access this computer." At the same time, if you issue OU rights in this domain, everything works.
Within one domain, this scheme works fine.
Log in attachment
[access-manager-service.log](https://github.com/lithnet/access-manager/files/5931403/access-manager-service.log)

 

Weblaps is a member of the Windows Authorization Access Group in all domains.

**Comment by ryannewington** [comment]
@Alex4e4 

This is definitely a permission issue. The service is getting an access denied message from the target DC when trying to read the group membership.

Is the gmsa a member of the access control assistance operators group in the target domain? Any restrictions on RPC access that you are aware of? Areas of the target AD where the gmsa doesn't have read access to?

**Comment by Alex4e4** [comment]
> @Alex4e4
> 
> This is definitely a permission issue. The service is getting an access denied message from the target DC when trying to read the group membership.
> 
> Is the gmsa a member of the access control assistance operators group in the target domain? Any restrictions on RPC access that you are aware of? Areas of the target AD where the gmsa doesn't have read access to?

**Comment by Alex4e4** [comment]
@ryannewington 
Thx, We add gMSA account to group Access Control Assistance Operators and this fix our problem. how safe is it to add an account to groups Access Control Assistance Operators and Windows Authorization Access Group?

**Comment by ryannewington** [comment]
Hi @Alex4e4 ,

Great question, both groups provide read-only access to authorization information.

The Windows Authorization Access Group allows the account to read the tokenGroups computed LDAP attribute on a security principal, essentially providing AMS with the list of global and university security groups that a user or computer is a member of.

The Access Control Assistance Operators allows us to use RPC to call into another domain and ask for an identification token for a user from the perspective of that domain. This also includes domain local groups from that domain.

Essentially they are providing AMS the ability to build authorization information. They don't have any other roles than that.

More information about the WAAG group -> https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/apps-apis-require-access

More information about ACAO -> https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#bkmk-acasstops
