### ISSUE TITLE
Ability to configure message to the user on the request screen

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#8]
When a user is presented with typing in computer name I would like to have ability to deliver some message on top - something like "Usage is strictly monitored, bla bla bla so that user is aware that "playing" with this will result with problems".

**Comment by ryannewington** [comment]
Can do

**Comment by ryannewington** [comment]
Hows this?

![image](https://user-images.githubusercontent.com/17229877/90748141-243cbc80-e315-11ea-9658-be0494a29569.png)

**Comment by PrzemyslawKlys** [comment]
You're making my dreams come true ;-)
