### ISSUE TITLE
JIT Access doesnt like long computer names

### ISSUE THREAD

**Issue by djclark46** [lithnet/access-manager#95]
We have a server called 

CATERINGEPOS-TEST

If we request access to this server we get the following

"The requested computer was not found in the directory"

<img width="559" alt="1" src="https://user-images.githubusercontent.com/61976271/119344464-9d47b680-bc8f-11eb-8607-881ceb443514.PNG">

If we enter the shortened form

CATERINGEPOS-TE

We can get the LAPS password but JIT access gives the following error.

"An unexpected error occurred during the authorization process"

<img width="424" alt="2" src="https://user-images.githubusercontent.com/61976271/119344388-85703280-bc8f-11eb-8bab-51f07dfd264a.PNG">

**Comment by ryannewington** [comment]
Thanks for reporting this @djclark46. There were a couple of issues where it was assumed the CN and the samAccountName would be the same value. This should now be resolved in the build linked below.

https://github.com/lithnet/access-manager/releases/tag/1.0.7925

Feel free to re-open this if it doesn't solve the problem for you
